// Recovered symbolic Script program from the frozen 3,425-byte leader.
// This is assembly source, not the missing historical CashScript/search pipeline.
// Function names describe recovered intent; stackSequence/towerSequence retain
// neutral names where a complete semantic contract has not yet been proved.
export const functions = [
  { name: 'fieldPrime', originalId: 1, body: `
    CALL curveSeedAndScalarMinusOne OP_1ADD OP_OVER OP_1SUB OP_DUP OP_MUL OP_MUL OP_3 OP_DIV OP_ADD
  ` },
  { name: 'subFp', originalId: 3, body: `
    OP_SWAP OP_SUB CALL fieldPrime OP_ADD CALL fieldPrime OP_MOD
  ` },
  { name: 'powFp', originalId: 30, body: `
    CALL fieldPrime OP_TUCK OP_MOD OP_1 OP_SWAP OP_0 OP_BEGIN OP_DUP OP_PUSHBYTES_2 0x7d01 OP_LESSTHAN OP_DUP
    OP_TOALTSTACK OP_IF OP_4 OP_PICK OP_OVER OP_RSHIFTNUM OP_2 OP_MOD OP_1 OP_NUMEQUAL OP_IF OP_ROT OP_2
    OP_PICK OP_MUL OP_3 OP_PICK OP_MOD OP_ROT OP_ROT OP_ENDIF OP_1ADD OP_OVER OP_ROT OP_MUL OP_3 OP_PICK
    OP_MOD OP_SWAP OP_ENDIF OP_FROMALTSTACK OP_NOT OP_UNTIL OP_2DROP OP_NIP OP_NIP
  ` },
  { name: 'inverseFp', originalId: 31, body: `
    CALL fieldPrime OP_2 OP_SUB OP_SWAP CALL powFp
  ` },
  { name: 'fp2Add', originalId: 4, body: `
    OP_ROT OP_ADD CALL fieldPrime OP_MOD OP_ROT OP_ROT OP_ADD CALL fieldPrime OP_MOD
  ` },
  { name: 'fp2Sub', originalId: 5, body: `
    OP_ROT OP_SWAP CALL subFp OP_ROT OP_ROT CALL subFp
  ` },
  { name: 'fp2Neg', originalId: 24, body: `
    OP_0 CALL subFp OP_SWAP OP_0 CALL subFp
  ` },
  { name: 'fp2Mul', originalId: 2, body: `
    OP_3 OP_PICK OP_2 OP_PICK OP_MUL CALL fieldPrime OP_MOD OP_3 OP_PICK OP_2 OP_PICK OP_MUL CALL fieldPrime
    OP_MOD CALL subFp OP_2SWAP OP_MUL CALL fieldPrime OP_MOD OP_2SWAP OP_MUL CALL fieldPrime OP_MOD OP_ADD
    CALL fieldPrime OP_MOD
  ` },
  { name: 'fp2Sqr', originalId: 7, body: `
    OP_2DUP CALL fp2Mul
  ` },
  { name: 'fp2MulXi', originalId: 13, body: `
    OP_2DUP CALL subFp OP_ROT OP_ROT OP_ADD CALL fieldPrime OP_MOD
  ` },
  { name: 'fp6Add', originalId: 17, body: `
    OP_7 OP_ROLL OP_7 OP_ROLL OP_2SWAP CALL fp2Add OP_7 OP_ROLL OP_7 OP_ROLL OP_2ROT CALL fp2Add OP_2ROT OP_7
    OP_ROLL OP_7 OP_ROLL OP_2SWAP CALL fp2Add
  ` },
  { name: 'fp6Sub', originalId: 32, body: `
    OP_7 OP_ROLL OP_7 OP_ROLL OP_2SWAP CALL fp2Sub OP_7 OP_ROLL OP_7 OP_ROLL OP_2ROT CALL fp2Sub OP_2ROT OP_7
    OP_ROLL OP_7 OP_ROLL OP_2SWAP CALL fp2Sub
  ` },
  { name: 'stackSequence33', originalId: 33, body: `
    OP_2ROT CALL fp2MulXi OP_2SWAP OP_SWAP OP_2ROT OP_SWAP
  ` },
  { name: 'fp6Mul', originalId: 18, body: `
    OP_7 OP_PICK OP_7 OP_PICK OP_2OVER CALL fp2Mul OP_11 OP_PICK OP_11 OP_PICK OP_5 OP_PICK OP_5 OP_PICK
    CALL fp2Mul OP_11 OP_PICK OP_11 OP_PICK OP_9 OP_PICK OP_9 OP_PICK CALL fp2Mul OP_SWAP OP_2SWAP OP_SWAP
    CALL fp2Add OP_15 OP_PICK OP_15 OP_PICK OP_7 OP_ROLL OP_7 OP_ROLL CALL fp2Mul OP_13 OP_PICK OP_13 OP_PICK
    OP_9 OP_PICK OP_9 OP_PICK CALL fp2Mul OP_SWAP OP_2SWAP OP_SWAP CALL fp2Add CALL stackSequence45 OP_13
    OP_PICK OP_13 OP_PICK OP_9 OP_ROLL OP_9 OP_ROLL CALL fp2Mul CALL stackSequence45 OP_SWAP CALL fp2MulXi
    OP_SWAP OP_6 OP_ROLL OP_7 OP_ROLL CALL fp2Add OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL
    CALL fp2Mul OP_SWAP CALL fp2MulXi OP_SWAP OP_6 OP_ROLL OP_7 OP_ROLL CALL fp2Add OP_2ROT
  ` },
  { name: 'fp12Sqr', originalId: 34, body: `
    CALL stackSequence29 CALL stackSequence29 CALL stackSequence9 CALL stackSequence9 CALL fp12Mul
  ` },
  { name: 'fp12Mul', originalId: 25, body: `
    CALL stackSequence20 CALL stackSequence20 CALL stackSequence29 CALL fp6Mul OP_PUSHBYTES_1 0x1d OP_PICK
    OP_PUSHBYTES_1 0x1d OP_PICK OP_PUSHBYTES_1 0x1d OP_PICK OP_PUSHBYTES_1 0x1d OP_PICK OP_PUSHBYTES_1 0x1d
    OP_PICK OP_PUSHBYTES_1 0x1d OP_PICK CALL stackSequence15 CALL fp6Mul CALL stackSequence9
    OP_PUSHBYTES_1 0x17 OP_PICK OP_PUSHBYTES_1 0x17 OP_PICK OP_PUSHBYTES_1 0x17 OP_PICK OP_PUSHBYTES_1 0x17
    OP_PICK OP_PUSHBYTES_1 0x17 OP_PICK OP_PUSHBYTES_1 0x17 OP_PICK CALL fp6Mul OP_SWAP OP_2SWAP OP_SWAP
    OP_2ROT OP_SWAP CALL stackSequence8 CALL fp6Add CALL stackSequence9 CALL stackSequence9 CALL fp6Mul
    OP_SWAP OP_2SWAP OP_SWAP OP_2ROT OP_SWAP CALL stackSequence33 OP_SWAP OP_2SWAP OP_SWAP OP_2ROT OP_SWAP
    CALL stackSequence10 CALL fp6Add CALL stackSequence6
  ` },
  { name: 'negFp', originalId: 35, body: `
    CALL fieldPrime OP_SWAP OP_SUB CALL fieldPrime OP_MOD
  ` },
  { name: 'fp2Scale', originalId: 14, body: `
    OP_2 OP_PICK OP_MUL CALL fieldPrime OP_MOD OP_ROT OP_ROT OP_MUL CALL fieldPrime OP_MOD
  ` },
  { name: 'fp2Half', originalId: 36, body: `

    OP_PUSHBYTES_48 0x56d5ffffff7fffdcffffa958ffff550f127b587b506998b35f89c279c2a53bb26bd6a521dbd38d254df3bf1cf588000d
    OP_TUCK OP_MUL CALL fieldPrime OP_MOD OP_SWAP OP_ROT OP_MUL CALL fieldPrime OP_MOD
  ` },
  { name: 'towerSequence37', originalId: 37, body: `
    OP_2OVER OP_2OVER CALL fp2Add OP_2OVER OP_9 OP_PICK OP_9 OP_PICK OP_2SWAP CALL fp2Add OP_SWAP OP_11
    OP_PICK OP_11 OP_PICK OP_2SWAP CALL fp2Mul OP_2ROT OP_11 OP_PICK OP_11 OP_PICK OP_2SWAP CALL fp2Mul
    OP_2DUP OP_SWAP OP_2ROT OP_SWAP CALL fp2Sub OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_PICK OP_9 OP_PICK
    CALL fp2Add OP_13 OP_PICK OP_13 OP_PICK OP_2SWAP OP_SWAP CALL fp2Mul OP_13 OP_PICK OP_13 OP_PICK OP_11
    OP_ROLL OP_11 OP_ROLL CALL fp2Mul OP_2DUP OP_SWAP OP_2ROT OP_SWAP CALL fp2Sub OP_SWAP CALL fp2MulXi
    OP_SWAP OP_6 OP_PICK OP_8 OP_PICK OP_2SWAP CALL fp2Add OP_2OVER OP_SWAP OP_6 OP_ROLL OP_7 OP_ROLL
    CALL fp2Add OP_13 OP_ROLL OP_13 OP_ROLL OP_13 OP_ROLL OP_13 OP_ROLL CALL fp2Add OP_SWAP OP_10 OP_ROLL
    OP_11 OP_ROLL OP_2SWAP CALL fp2Mul CALL stackSequence47 OP_SWAP OP_6 OP_ROLL OP_7 OP_ROLL OP_2SWAP
    CALL fp2Sub OP_2SWAP
  ` },
  { name: 'towerSequence38', originalId: 38, body: `
    OP_PUSHBYTES_1 0x13 OP_PICK OP_PUSHBYTES_1 0x12 OP_ROLL OP_MUL CALL fieldPrime OP_MOD OP_PUSHBYTES_1 0x13
    OP_ROLL OP_PUSHBYTES_1 0x12 OP_ROLL OP_MUL CALL fieldPrime OP_MOD OP_PUSHBYTES_1 0x12 OP_PICK
    OP_PUSHBYTES_1 0x12 OP_ROLL OP_MUL CALL fieldPrime OP_MOD OP_PUSHBYTES_1 0x12 OP_ROLL OP_PUSHBYTES_1 0x12
    OP_ROLL OP_MUL CALL fieldPrime OP_MOD CALL stackSequence15 CALL stackSequence15 OP_PUSHBYTES_1 0x11
    OP_ROLL OP_PUSHBYTES_1 0x11 OP_ROLL OP_2OVER OP_7 OP_PICK OP_7 OP_PICK OP_2SWAP OP_5 OP_PICK OP_5 OP_PICK
    CALL stackSequence20 CALL stackSequence20 CALL fp6Add OP_PUSHBYTES_1 0x15 OP_PICK OP_PUSHBYTES_1 0x15
    OP_PICK OP_PUSHBYTES_1 0x15 OP_PICK OP_PUSHBYTES_1 0x15 OP_PICK OP_15 OP_ROLL OP_15 OP_ROLL OP_15 OP_ROLL
    OP_15 OP_ROLL OP_15 OP_ROLL OP_15 OP_ROLL CALL towerSequence37 OP_PUSHBYTES_1 0x17 OP_PICK
    OP_PUSHBYTES_1 0x17 OP_PICK OP_PUSHBYTES_1 0x17 OP_ROLL OP_PUSHBYTES_1 0x17 OP_ROLL CALL fp2Add OP_SWAP
    OP_PUSHBYTES_1 0x15 OP_ROLL OP_PUSHBYTES_1 0x15 OP_ROLL OP_10 OP_ROLL OP_11 OP_ROLL OP_12 OP_ROLL OP_13
    OP_ROLL OP_14 OP_ROLL OP_15 OP_ROLL CALL towerSequence37 OP_6 OP_PICK OP_8 OP_PICK OP_10 OP_PICK OP_12
    OP_PICK OP_14 OP_PICK OP_16 OP_PICK CALL stackSequence8 CALL fp6Sub CALL stackSequence50
    CALL stackSequence50 OP_2ROT OP_7 OP_PICK OP_7 OP_PICK OP_2SWAP CALL fp2Mul OP_SWAP CALL fp2MulXi OP_7
    OP_PICK OP_7 OP_PICK OP_2ROT CALL fp2Mul OP_2ROT OP_7 OP_ROLL OP_7 OP_ROLL OP_2SWAP CALL fp2Mul OP_DUP
    OP_2OVER OP_SWAP OP_6 OP_PICK OP_8 OP_PICK OP_10 OP_PICK CALL stackSequence10 CALL fp6Sub
    CALL stackSequence8 CALL stackSequence33 CALL stackSequence10 CALL stackSequence8 CALL fp6Add
    CALL stackSequence6
  ` },
  { name: 'millerAccumulate', originalId: 26, body: `
    CALL stackSequence15 CALL millerLoop OP_SWAP OP_2SWAP OP_SWAP OP_2ROT OP_SWAP CALL stackSequence8
    CALL stackSequence9 CALL stackSequence9 CALL fp12Mul
  ` },
  { name: 'millerLoop', originalId: 39, body: `
    CALL stackSequence51 OP_12 OP_PICK OP_14 OP_PICK OP_16 OP_PICK OP_PUSHBYTES_1 0x12 OP_PICK OP_1 OP_0 OP_0
    OP_BEGIN OP_DUP OP_PUSHBYTES_1 0x40 OP_LESSTHAN OP_DUP OP_TOALTSTACK OP_IF OP_SWAP OP_2SWAP OP_SWAP
    OP_2ROT OP_SWAP OP_6 OP_ROLL OP_2OVER CALL fp2Sqr OP_7 OP_PICK OP_7 OP_PICK CALL fp2Sqr OP_3 OP_OVER OP_3
    OP_PICK CALL fp2Scale OP_SWAP OP_4 OP_MUL CALL fieldPrime OP_MOD OP_4 OP_ROT OP_MUL CALL fieldPrime
    OP_MOD OP_2DUP OP_SWAP CALL subFp OP_SWAP OP_ROT OP_ADD CALL fieldPrime OP_MOD OP_4 OP_PICK OP_6 OP_PICK
    OP_2OVER OP_SWAP CALL fp2Sub OP_9 OP_PICK OP_9 OP_PICK CALL fp2Sqr OP_3 OP_SWAP OP_ROT CALL fp2Scale
    OP_15 OP_ROLL OP_15 OP_ROLL OP_15 OP_PICK OP_15 OP_PICK CALL fp2Add OP_SWAP CALL fp2Sqr
    CALL stackSequence47 OP_SWAP OP_8 OP_PICK OP_10 OP_PICK OP_2SWAP CALL fp2Sub OP_2DUP OP_SWAP CALL fp2Neg
    OP_3 OP_9 OP_PICK OP_11 OP_PICK CALL fp2Scale OP_2DUP OP_SWAP OP_14 OP_PICK OP_16 OP_PICK CALL fp2Sub
    OP_PUSHBYTES_1 0x11 OP_ROLL OP_PUSHBYTES_1 0x11 OP_ROLL OP_2SWAP OP_SWAP CALL fp2Mul OP_PUSHBYTES_1 0x11
    OP_ROLL OP_PUSHBYTES_1 0x11 OP_ROLL OP_2SWAP OP_SWAP CALL fp2Mul OP_SWAP CALL fp2Half OP_12 OP_ROLL OP_13
    OP_ROLL CALL fp2Sqr OP_3 OP_SWAP OP_ROT CALL fp2Scale OP_2ROT OP_SWAP OP_14 OP_PICK OP_16 OP_PICK
    CALL fp2Add OP_SWAP CALL fp2Half OP_SWAP CALL fp2Sqr OP_3 OP_ROLL OP_SWAP OP_ROT CALL fp2Sub OP_6 OP_ROLL
    OP_7 OP_ROLL OP_12 OP_ROLL OP_13 OP_ROLL CALL fp2Mul OP_13 OP_ROLL OP_14 OP_ROLL OP_15 OP_ROLL OP_16
    OP_ROLL OP_PUSHBYTES_1 0x11 OP_ROLL CALL stackSequence43 OP_PUSHBYTES_1 0x18 OP_ROLL CALL fp12Sqr
    OP_PUSHBYTES_1 0x1e OP_PICK OP_PUSHBYTES_1 0x1e OP_PICK OP_PUSHBYTES_1 0x14 OP_PICK OP_PUSHBYTES_1 0x16
    OP_PICK OP_PUSHBYTES_1 0x18 OP_PICK OP_PUSHBYTES_1 0x1a OP_PICK OP_PUSHBYTES_1 0x1c OP_PICK
    OP_PUSHBYTES_1 0x1e OP_PICK CALL stackSequence41 OP_PUSHBYTES_1 0x1a OP_PICK OP_PUSHBYTES_1 0x1c OP_PICK
    OP_PUSHBYTES_1 0x1e OP_PICK CALL towerSequence38 OP_PUSHBYTES_7 0x4a800000008000 OP_PUSHBYTES_1 0x25
    OP_PICK OP_RSHIFTNUM OP_2 OP_MOD OP_DUP OP_1 OP_NUMEQUAL CALL stackSequence48 CALL stackSequence48
    CALL stackSequence48 OP_PUSHBYTES_1 0x2b OP_PICK OP_PUSHBYTES_1 0x2b OP_PICK OP_PUSHBYTES_1 0x2b OP_PICK
    OP_PUSHBYTES_1 0x2b OP_PICK OP_PUSHBYTES_1 0x2b OP_PICK OP_PUSHBYTES_1 0x2b OP_PICK OP_PUSHBYTES_1 0x38
    OP_ROLL CALL stackSequence21 CALL stackSequence21 CALL stackSequence21 CALL stackSequence21
    CALL stackSequence16 CALL stackSequence16 CALL stackSequence16 CALL stackSequence16 CALL stackSequence16
    OP_PUSHBYTES_1 0x38 OP_ROLL OP_IF OP_2 OP_PUSHBYTES_1 0x26 OP_PICK OP_RSHIFTNUM OP_2 OP_MOD
    OP_PUSHBYTES_1 0x3b OP_PICK OP_PUSHBYTES_1 0x3d OP_PICK OP_2 OP_PICK OP_1 OP_NUMEQUAL OP_IF
    OP_PUSHBYTES_1 0x3e OP_PICK OP_PUSHBYTES_1 0x3e OP_PICK CALL fp2Neg OP_2SWAP OP_2DROP OP_ENDIF OP_SWAP
    OP_PUSHBYTES_1 0x3c OP_PICK OP_PUSHBYTES_1 0x3c OP_PICK OP_PUSHBYTES_1 0x2b OP_ROLL OP_PUSHBYTES_1 0x2c
    OP_ROLL OP_PUSHBYTES_1 0x2d OP_ROLL OP_PUSHBYTES_1 0x2e OP_ROLL OP_PUSHBYTES_1 0x2f OP_ROLL
    OP_PUSHBYTES_1 0x30 OP_ROLL OP_5 OP_PICK OP_5 OP_PICK OP_9 OP_PICK OP_9 OP_PICK CALL fp2Mul OP_SWAP
    OP_2OVER CALL fp2Sub OP_2DUP OP_SWAP CALL fp2Sqr OP_2OVER OP_SWAP OP_2OVER OP_SWAP CALL fp2Mul OP_7
    OP_ROLL OP_7 OP_ROLL OP_2ROT OP_SWAP CALL fp2Mul OP_2 OP_OVER OP_3 OP_PICK CALL fp2Scale OP_SWAP OP_4
    OP_PICK OP_6 OP_PICK CALL fp2Sub OP_9 OP_PICK OP_9 OP_PICK OP_6 OP_PICK OP_8 OP_PICK CALL fp2Mul OP_6
    OP_ROLL OP_7 OP_ROLL OP_13 OP_PICK OP_13 OP_PICK CALL fp2Mul OP_PUSHBYTES_1 0x11 OP_PICK
    OP_PUSHBYTES_1 0x11 OP_PICK OP_10 OP_PICK OP_12 OP_PICK CALL fp2Mul OP_15 OP_PICK OP_15 OP_PICK
    OP_PUSHBYTES_1 0x15 OP_ROLL OP_PUSHBYTES_1 0x15 OP_ROLL CALL fp2Mul OP_SWAP OP_15 OP_ROLL OP_15 OP_ROLL
    CALL fp2Sub OP_2DUP OP_SWAP CALL fp2Neg OP_2OVER OP_SWAP CALL fp2Sqr OP_PUSHBYTES_1 0x13 OP_ROLL
    OP_PUSHBYTES_1 0x13 OP_ROLL OP_2SWAP OP_SWAP CALL fp2Mul OP_SWAP OP_12 OP_ROLL OP_13 OP_ROLL CALL fp2Add
    OP_2DUP OP_SWAP OP_14 OP_ROLL OP_15 OP_ROLL CALL fp2Sub OP_SWAP OP_6 OP_PICK OP_8 OP_PICK OP_2SWAP
    CALL fp2Mul OP_12 OP_ROLL OP_13 OP_ROLL OP_2SWAP OP_SWAP CALL fp2Sub OP_2SWAP OP_SWAP OP_12 OP_PICK OP_14
    OP_PICK CALL fp2Mul OP_15 OP_ROLL OP_15 OP_ROLL OP_8 OP_ROLL OP_9 OP_ROLL CALL fp2Mul
    CALL stackSequence47 OP_7 OP_ROLL OP_7 OP_ROLL OP_2ROT OP_11 OP_ROLL OP_11 OP_ROLL OP_2SWAP OP_9 OP_ROLL
    OP_9 OP_ROLL OP_11 OP_ROLL OP_11 OP_ROLL OP_PUSHBYTES_1 0x44 OP_PICK OP_PUSHBYTES_1 0x44 OP_PICK
    CALL stackSequence46 OP_12 OP_ROLL OP_13 OP_ROLL OP_PUSHBYTES_1 0x35 OP_ROLL OP_PUSHBYTES_1 0x36 OP_ROLL
    OP_PUSHBYTES_1 0x37 OP_ROLL OP_PUSHBYTES_1 0x38 OP_ROLL OP_PUSHBYTES_1 0x39 OP_ROLL OP_PUSHBYTES_1 0x3a
    OP_ROLL OP_PUSHBYTES_1 0x3b OP_ROLL OP_PUSHBYTES_1 0x3c OP_ROLL OP_PUSHBYTES_1 0x3d OP_ROLL
    OP_PUSHBYTES_1 0x3e OP_ROLL OP_PUSHBYTES_1 0x3f OP_ROLL OP_PUSHBYTES_1 0x40 OP_ROLL CALL towerSequence38
    OP_PUSHBYTES_1 0x12 OP_ROLL OP_DROP CALL stackSequence6 CALL stackSequence6 CALL stackSequence15
    CALL stackSequence12 CALL stackSequence12 CALL stackSequence12 CALL stackSequence12 CALL stackSequence12
    CALL stackSequence12 OP_PUSHBYTES_1 0x37 OP_ROLL OP_PUSHBYTES_1 0x37 OP_ROLL OP_ENDIF OP_PUSHBYTES_1 0x25
    OP_ROLL OP_1ADD CALL stackSequence23 CALL stackSequence23 CALL stackSequence23 CALL stackSequence23
    OP_NIP OP_ENDIF OP_FROMALTSTACK OP_NOT OP_UNTIL OP_2DROP OP_2DROP OP_2DROP OP_DROP OP_12 OP_ROLL OP_DROP
    OP_12 OP_ROLL OP_DROP OP_12 OP_ROLL OP_DROP OP_12 OP_ROLL OP_DROP OP_12 OP_ROLL OP_DROP OP_12 OP_ROLL
    OP_DROP CALL stackSequence6 CALL stackSequence6
  ` },
  { name: 'g1Double', originalId: 40, body: `
    OP_DUP OP_DUP OP_MUL CALL fieldPrime OP_MOD OP_2 OP_PICK OP_DUP OP_MUL CALL fieldPrime OP_MOD OP_DUP
    OP_DUP OP_MUL CALL fieldPrime OP_MOD OP_TUCK OP_3 OP_PICK OP_ROT OP_5 OP_ROLL OP_ADD CALL stackSequence49
    CALL subFp CALL subFp OP_2 OP_MUL CALL fieldPrime OP_MOD OP_ROT OP_3 OP_MUL CALL fieldPrime OP_MOD OP_DUP
    OP_DUP OP_MUL CALL fieldPrime OP_MOD OP_2 OP_PICK OP_2 OP_MUL CALL fieldPrime OP_MOD OP_SWAP CALL subFp
    OP_3 OP_ROLL OP_8 CALL stackSequence44 OP_2SWAP OP_MUL CALL fieldPrime OP_MOD OP_2 OP_MUL CALL fieldPrime
    OP_MOD
  ` },
  { name: 'g1Add', originalId: 27, body: `
    OP_3 OP_PICK OP_5 OP_PICK OP_1 OP_5 OP_PICK OP_0 OP_NUMNOTEQUAL OP_IF OP_5 OP_PICK OP_DUP OP_MUL
    CALL fieldPrime OP_MOD OP_DUP OP_8 OP_PICK OP_MUL CALL fieldPrime OP_MOD OP_OVER OP_8 OP_PICK OP_11
    OP_PICK OP_MUL CALL fieldPrime OP_MOD OP_MUL CALL fieldPrime OP_MOD OP_6 OP_PICK OP_2 OP_PICK OP_NUMEQUAL
    OP_8 OP_PICK OP_2 OP_PICK OP_NUMEQUAL OP_BOOLAND OP_IF OP_8 OP_PICK OP_8 OP_PICK OP_8 OP_PICK
    CALL g1Double OP_6 OP_ROLL OP_7 OP_ROLL OP_2DROP OP_2ROT OP_6 OP_ROLL OP_DROP OP_5 OP_ROLL OP_ELSE OP_6
    OP_PICK OP_2 OP_PICK CALL subFp OP_DUP OP_2 OP_MUL CALL stackSequence49 OP_DUP OP_9 OP_PICK OP_MUL
    CALL fieldPrime OP_MOD OP_DUP OP_2 OP_MUL CALL fieldPrime OP_MOD OP_3 OP_PICK OP_3 OP_ROLL OP_MUL
    CALL fieldPrime OP_MOD OP_11 OP_PICK OP_5 OP_PICK CALL subFp OP_2 OP_MUL CALL fieldPrime OP_MOD OP_DUP
    OP_OVER OP_MUL CALL fieldPrime OP_MOD OP_2 OP_PICK OP_SWAP CALL subFp OP_3 OP_ROLL OP_SWAP CALL subFp
    OP_ROT OP_12 OP_PICK OP_MUL CALL fieldPrime OP_MOD OP_2 CALL stackSequence44 OP_1 OP_12 OP_PICK OP_ADD
    CALL stackSequence49 OP_6 OP_PICK OP_SWAP CALL subFp OP_1 OP_SWAP CALL subFp OP_3 OP_ROLL OP_SWAP OP_MUL
    CALL fieldPrime OP_MOD OP_6 OP_ROLL OP_7 OP_ROLL OP_2DROP OP_2ROT OP_6 OP_ROLL OP_DROP OP_5 OP_ROLL
    OP_ENDIF OP_2DROP OP_DROP OP_ENDIF OP_DUP OP_2ROT OP_2DROP OP_2ROT OP_2DROP OP_4 OP_ROLL OP_2DROP
  ` },
  { name: 'sqrtFp', originalId: 28, body: `
    CALL fieldPrime OP_1ADD OP_4 OP_DIV OP_SWAP CALL powFp
  ` },
  { name: 'decompressG1', originalId: 11, body: `
    OP_4 OP_OVER OP_DUP OP_DUP OP_MUL CALL fieldPrime OP_MOD OP_MUL CALL fieldPrime OP_MOD OP_ADD
    CALL fieldPrime OP_MOD CALL sqrtFp OP_DUP OP_3 OP_ROLL OP_1 OP_NUMEQUAL OP_IF OP_OVER CALL negFp OP_NIP
    OP_ENDIF OP_NIP OP_NIP
  ` },
  { name: 'decompressG2', originalId: 19, body: `
    CALL fieldPrime OP_2 OP_PICK OP_2 OP_PICK CALL fp2Sqr OP_4 OP_ROLL OP_4 OP_ROLL OP_2SWAP OP_SWAP
    CALL fp2Mul OP_4 OP_4 OP_2SWAP OP_SWAP CALL fp2Add OP_OVER OP_DUP OP_MUL OP_3 OP_PICK OP_MOD OP_OVER
    OP_DUP OP_MUL OP_4 OP_PICK OP_MOD OP_ADD OP_3 OP_PICK OP_MOD CALL sqrtFp OP_DUP OP_5 OP_ROLL OP_1
    OP_NUMEQUAL OP_IF OP_4 OP_PICK OP_2 OP_PICK OP_SUB OP_NIP OP_ENDIF OP_4 OP_PICK OP_1ADD OP_2 OP_DIV OP_4
    OP_ROLL OP_ROT OP_ADD OP_4 OP_PICK OP_MOD OP_MUL OP_3 OP_PICK OP_MOD CALL sqrtFp OP_DUP OP_5 OP_ROLL OP_1
    OP_NUMEQUAL OP_IF OP_4 OP_PICK OP_2 OP_PICK OP_SUB OP_NIP OP_ENDIF OP_3 OP_ROLL OP_2 OP_2 OP_PICK OP_MUL
    OP_5 OP_PICK OP_MOD CALL inverseFp OP_MUL OP_4 OP_ROLL OP_MOD OP_2SWAP OP_2DROP
  ` },
  { name: 'stackSequence9', originalId: 9, body: `
    OP_PUSHBYTES_1 0x17 OP_ROLL OP_PUSHBYTES_1 0x17 OP_ROLL OP_PUSHBYTES_1 0x17 OP_ROLL OP_PUSHBYTES_1 0x17
    OP_ROLL OP_PUSHBYTES_1 0x17 OP_ROLL OP_PUSHBYTES_1 0x17 OP_ROLL
  ` },
  { name: 'stackSequence6', originalId: 6, body: `
    OP_11 OP_ROLL OP_11 OP_ROLL OP_11 OP_ROLL OP_11 OP_ROLL OP_11 OP_ROLL OP_11 OP_ROLL
  ` },
  { name: 'stackSequence12', originalId: 12, body: `
    OP_PUSHBYTES_1 0x37 OP_ROLL OP_PUSHBYTES_1 0x37 OP_ROLL OP_PUSHBYTES_1 0x37 OP_ROLL OP_PUSHBYTES_1 0x37
    OP_ROLL OP_PUSHBYTES_1 0x37 OP_ROLL OP_PUSHBYTES_1 0x37 OP_ROLL
  ` },
  { name: 'stackSequence8', originalId: 8, body: `
    OP_6 OP_ROLL OP_7 OP_ROLL CALL stackSequence46
  ` },
  { name: 'stackSequence10', originalId: 10, body: `
    OP_12 OP_ROLL OP_13 OP_ROLL OP_14 OP_ROLL OP_15 OP_ROLL OP_16 OP_ROLL OP_PUSHBYTES_1 0x11 OP_ROLL
  ` },
  { name: 'stackSequence15', originalId: 15, body: `
    OP_PUSHBYTES_1 0x11 OP_ROLL OP_PUSHBYTES_1 0x11 OP_ROLL OP_PUSHBYTES_1 0x11 OP_ROLL OP_PUSHBYTES_1 0x11
    OP_ROLL OP_PUSHBYTES_1 0x11 OP_ROLL OP_PUSHBYTES_1 0x11 OP_ROLL
  ` },
  { name: 'stackSequence16', originalId: 16, body: `
    OP_PUSHBYTES_1 0x38 OP_ROLL OP_PUSHBYTES_1 0x38 OP_ROLL OP_PUSHBYTES_1 0x38 OP_ROLL OP_PUSHBYTES_1 0x38
    OP_ROLL OP_PUSHBYTES_1 0x38 OP_ROLL
  ` },
  { name: 'stackSequence41', originalId: 41, body: `
    OP_8 OP_PICK OP_10 OP_PICK OP_12 OP_PICK OP_14 OP_PICK OP_16 OP_PICK OP_PUSHBYTES_1 0x12 OP_PICK
    OP_PUSHBYTES_1 0x14 OP_PICK OP_PUSHBYTES_1 0x16 OP_PICK OP_PUSHBYTES_1 0x18 OP_PICK
  ` },
  { name: 'stackSequence20', originalId: 20, body: `
    OP_PUSHBYTES_1 0x11 OP_PICK OP_PUSHBYTES_1 0x11 OP_PICK OP_PUSHBYTES_1 0x11 OP_PICK
  ` },
  { name: 'stackSequence21', originalId: 21, body: `
    OP_PUSHBYTES_1 0x2c OP_ROLL OP_PUSHBYTES_1 0x2c OP_ROLL OP_PUSHBYTES_1 0x2c OP_ROLL
  ` },
  { name: 'stackSequence22', originalId: 22, body: `
    OP_PUSHBYTES_1 0x19 OP_ROLL OP_PUSHBYTES_1 0x19 OP_ROLL OP_PUSHBYTES_1 0x19 OP_ROLL
  ` },
  { name: 'stackSequence23', originalId: 23, body: `
    OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP
  ` },
  { name: 'stackSequence29', originalId: 29, body: `
    OP_11 OP_PICK OP_11 OP_PICK OP_11 OP_PICK OP_11 OP_PICK OP_11 OP_PICK OP_11 OP_PICK
  ` },
  { name: 'curveSeedAndScalarMinusOne', originalId: 42, body: `
    CONST BLS_X OP_DUP OP_DUP OP_MUL OP_DUP OP_DUP OP_MUL OP_SWAP OP_SUB
  ` },
  { name: 'stackSequence43', originalId: 43, body: `
    OP_PUSHBYTES_1 0x12 OP_ROLL OP_PUSHBYTES_1 0x13 OP_ROLL OP_PUSHBYTES_1 0x14 OP_ROLL OP_PUSHBYTES_1 0x15
    OP_ROLL OP_PUSHBYTES_1 0x16 OP_ROLL OP_PUSHBYTES_1 0x17 OP_ROLL
  ` },
  { name: 'stackSequence44', originalId: 44, body: `
    OP_MUL CALL fieldPrime OP_MOD OP_OVER OP_4 OP_ROLL CALL subFp OP_3 OP_ROLL OP_MUL CALL fieldPrime OP_MOD
    CALL subFp
  ` },
  { name: 'stackSequence45', originalId: 45, body: `
    OP_11 OP_ROLL OP_11 OP_ROLL OP_11 OP_PICK OP_11 OP_PICK CALL fp2Mul OP_SWAP OP_2SWAP OP_SWAP CALL fp2Add
  ` },
  { name: 'stackSequence46', originalId: 46, body: `
    OP_8 OP_ROLL OP_9 OP_ROLL OP_10 OP_ROLL OP_11 OP_ROLL
  ` },
  { name: 'stackSequence47', originalId: 47, body: `
    OP_SWAP OP_8 OP_ROLL OP_9 OP_ROLL OP_2SWAP CALL fp2Sub
  ` },
  { name: 'stackSequence48', originalId: 48, body: `
    OP_13 OP_PICK OP_13 OP_PICK OP_13 OP_PICK OP_13 OP_PICK
  ` },
  { name: 'stackSequence49', originalId: 49, body: `
    CALL fieldPrime OP_MOD OP_DUP OP_MUL CALL fieldPrime OP_MOD
  ` },
  { name: 'stackSequence50', originalId: 50, body: `
    OP_PUSHBYTES_1 0x13 OP_ROLL OP_PUSHBYTES_1 0x13 OP_ROLL OP_PUSHBYTES_1 0x13 OP_ROLL OP_PUSHBYTES_1 0x13
    OP_ROLL
  ` },
  { name: 'stackSequence51', originalId: 51, body: `
    OP_1 OP_0 OP_0 OP_0 OP_0 OP_0 OP_0 OP_0 OP_0 OP_0 OP_0 OP_0
  ` },
];

export const main = `
    OP_TUCK CALL decompressG1 OP_2ROT OP_5 OP_PICK OP_5 OP_PICK CALL decompressG2 OP_7 OP_ROLL OP_7 OP_PICK
    CALL decompressG1
    OP_PUSHBYTES_48 0x4e0fbf29558c9ac3427c1c8fbb758fe22aa658c30a2d90432501289130db21970c45a950ebc8088846674d90eacb7205
    OP_1 OP_OVER CALL decompressG1
    OP_PUSHBYTES_48 0x605b9bfff38785e0134b69ccde04eb7f892c58ec675cbb0958d65ba3b07aa7e9192fa0c5b7448a3a66d5cbafd5609b0c
    OP_0 OP_OVER CALL decompressG1
    OP_PUSHBYTES_48 0x09b9ad0c3a118338d312729d5244979a2a9e2ad16649894c73206b09d14f9405facc9e328f7dd2c5850f52a46d2fe806
    OP_1 OP_OVER CALL decompressG1 OP_0 OP_1 OP_0 OP_0 OP_BEGIN OP_DUP OP_PUSHBYTES_2 0xff00 OP_LESSTHAN
    OP_DUP OP_TOALTSTACK OP_IF OP_PUSHBYTES_2 0xfe00 OP_OVER OP_SUB OP_2 OP_PICK OP_0 OP_NUMNOTEQUAL OP_4
    OP_PICK OP_0 OP_NUMNOTEQUAL OP_BOOLAND OP_IF OP_2SWAP OP_SWAP OP_4 OP_ROLL CALL g1Double OP_4 OP_ROLL
    OP_4 OP_ROLL OP_ENDIF OP_PUSHBYTES_1 0x13 OP_PICK OP_OVER OP_RSHIFTNUM OP_2 OP_MOD OP_1 OP_NUMEQUAL OP_IF
    OP_7 OP_PICK OP_9 OP_PICK OP_2ROT OP_SWAP OP_6 OP_ROLL CALL g1Add OP_4 OP_ROLL OP_4 OP_ROLL OP_ENDIF
    OP_PUSHBYTES_1 0x14 OP_PICK OP_OVER OP_RSHIFTNUM OP_2 OP_MOD OP_1 OP_NUMEQUAL OP_IF OP_5 OP_PICK OP_7
    OP_PICK OP_2ROT OP_SWAP OP_6 OP_ROLL CALL g1Add OP_4 OP_ROLL OP_4 OP_ROLL OP_ENDIF OP_SWAP OP_1ADD OP_NIP
    OP_ENDIF OP_FROMALTSTACK OP_NOT OP_UNTIL OP_13 OP_ROLL CALL negFp OP_14 OP_ROLL OP_13 OP_ROLL OP_14
    OP_ROLL OP_16 OP_ROLL OP_16 OP_ROLL CALL millerLoop OP_PUSHBYTES_1 0x14 OP_ROLL OP_PUSHBYTES_1 0x15
    OP_ROLL OP_15 OP_PICK OP_PUSHBYTES_1 0x11 OP_PICK OP_PUSHBYTES_1 0x13 OP_PICK CALL g1Add CALL inverseFp
    OP_DUP OP_OVER OP_MUL CALL fieldPrime OP_MOD OP_DUP OP_4 OP_ROLL OP_MUL OP_ROT OP_ROT OP_MUL
    CALL fieldPrime OP_MOD OP_ROT OP_MUL CALL fieldPrime OP_ROT OP_SWAP OP_MOD CALL fieldPrime OP_ROT OP_SWAP
    OP_MOD
    OP_PUSHBYTES_48 0x24524e02c9c0d2969b17a22c0b7a7481f93f5b33510a78f3f1a5e99b1fd612b19796a9ec2d21651713f0d1f908e3ec09
    OP_0 OP_OVER CALL decompressG1
    OP_PUSHBYTES_48 0xd694a841c67d9dee70a7a1e9c59670f99c7012f1af3b18dd864a23c16333971d126c8b6046db293321a8db047883fb00
    OP_PUSHBYTES_48 0x8826df68143dff8e54b02430684dd1fc04f0b69df41fcb624512de782310f1c08c02651df2a971e6ecff3067dea51104
    OP_1 OP_0 OP_2OVER CALL decompressG2 OP_SWAP OP_2ROT OP_SWAP OP_2SWAP OP_2ROT CALL stackSequence46
    CALL stackSequence10 OP_PUSHBYTES_1 0x12 OP_ROLL OP_PUSHBYTES_1 0x13 OP_ROLL CALL millerAccumulate
    OP_PUSHBYTES_48 0xc83472247446b1bdd44416ad1c1f929a3f01ed345be35b9b4ba20f17ccf2b5208e3dec8380d6b8c337ed31bff673020d
    OP_PUSHBYTES_48 0x3c8dd3f68a360f9c5ba81fad2be3408bdc3070619bc7bf3794851bd623685a5036ef5f1388c0541e58c3d2b2dbd19c04
    OP_1 OP_0 OP_2OVER CALL decompressG2 OP_16 OP_ROLL OP_PUSHBYTES_1 0x11 OP_ROLL OP_2SWAP OP_SWAP OP_2ROT
    CALL stackSequence8 CALL stackSequence10 CALL millerAccumulate
    OP_PUSHBYTES_48 0xb0f140ae9075fba0c7550369e8c32bc285da7edc9ce5b7afabca4cf0d32e98a6299ea2e0bf0533398422607d85be9001
    OP_PUSHBYTES_48 0xe3bc09eee13aa5b98e269629ee5cef196eba9ff9da8c713622d0b50e5c3520d65e3d88dfb60251a389e268d5043f3009
    OP_0 OP_1 OP_2OVER CALL decompressG2 OP_PUSHBYTES_1 0x18 OP_ROLL OP_PUSHBYTES_1 0x19 OP_ROLL OP_2SWAP
    OP_SWAP OP_2ROT CALL stackSequence8 CALL stackSequence10 CALL millerAccumulate OP_SWAP OP_2SWAP OP_SWAP
    OP_2ROT OP_SWAP CALL stackSequence8 CALL stackSequence51 CALL stackSequence10 CALL stackSequence43
    CALL curveSeedAndScalarMinusOne OP_1 OP_ADD OP_OVER OP_1 OP_SUB OP_DUP OP_MUL OP_OVER OP_MUL OP_3 OP_DIV
    OP_ROT OP_ADD OP_DUP OP_MUL OP_DUP OP_MUL OP_DUP OP_DUP OP_MUL OP_MUL OP_1 OP_SUB OP_SWAP OP_DIV OP_0
    OP_BEGIN OP_DUP OP_PUSHBYTES_2 0xda10 OP_LESSTHAN OP_DUP OP_TOALTSTACK OP_IF OP_2DUP OP_RSHIFTNUM OP_2
    OP_MOD OP_1 OP_NUMEQUAL OP_IF OP_2OVER OP_SWAP OP_6 OP_PICK CALL stackSequence41 OP_PUSHBYTES_1 0x1a
    OP_ROLL OP_PUSHBYTES_1 0x1b OP_ROLL OP_PUSHBYTES_1 0x1c OP_ROLL OP_PUSHBYTES_1 0x1d OP_ROLL
    OP_PUSHBYTES_1 0x1e OP_ROLL OP_PUSHBYTES_1 0x1f OP_ROLL OP_PUSHBYTES_1 0x20 OP_ROLL OP_PUSHBYTES_1 0x21
    OP_ROLL OP_PUSHBYTES_1 0x22 OP_ROLL OP_PUSHBYTES_1 0x23 OP_ROLL OP_PUSHBYTES_1 0x24 OP_ROLL
    OP_PUSHBYTES_1 0x25 OP_ROLL CALL fp12Mul CALL stackSequence6 CALL stackSequence6 CALL stackSequence22
    CALL stackSequence22 CALL stackSequence22 CALL stackSequence22 OP_PUSHBYTES_1 0x19 OP_ROLL
    OP_PUSHBYTES_1 0x19 OP_ROLL OP_ENDIF OP_1ADD OP_2SWAP OP_SWAP OP_2ROT OP_SWAP CALL stackSequence8 OP_12
    OP_ROLL OP_13 OP_ROLL CALL fp12Sqr CALL stackSequence6 CALL stackSequence6 OP_13 OP_ROLL OP_13 OP_ROLL
    OP_ENDIF OP_FROMALTSTACK OP_NOT OP_UNTIL OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP
    OP_12 OP_ROLL OP_DROP OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL
    OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_11 OP_ROLL OP_1
    OP_NUMEQUALVERIFY OP_10 OP_ROLL OP_0 OP_NUMEQUALVERIFY OP_9 OP_ROLL OP_0 OP_NUMEQUALVERIFY OP_8 OP_ROLL
    OP_0 OP_NUMEQUALVERIFY OP_7 OP_ROLL OP_0 OP_NUMEQUALVERIFY OP_6 OP_ROLL OP_0 OP_NUMEQUALVERIFY OP_5
    OP_ROLL OP_0 OP_NUMEQUALVERIFY OP_4 OP_ROLL OP_0 OP_NUMEQUALVERIFY OP_3 OP_ROLL OP_0 OP_NUMEQUALVERIFY
    OP_ROT OP_0 OP_NUMEQUALVERIFY OP_SWAP OP_0 OP_NUMEQUALVERIFY OP_0 OP_NUMEQUALVERIFY OP_2DROP OP_2DROP
    OP_2DROP OP_2DROP OP_DROP OP_1
`;
