// Exact recovered shared assembly. Neutral sequence names make no unproved
// arithmetic claim. Original IDs, declaration order and stack dispatch are preserved.
export const prefix = `

`;

export const functions = [
  { name: 'readBoundedInputSlice', originalId: 0, body: `
    OP_DUP OP_INPUTBYTECODE OP_SIZE OP_NIP OP_2OVER OP_ADD OP_GREATERTHANOREQUAL OP_VERIFY OP_INPUTBYTECODE
    OP_OVER OP_SPLIT OP_SWAP OP_SIZE OP_NIP OP_ROT OP_NUMEQUALVERIFY OP_OVER OP_SPLIT OP_DROP OP_DUP OP_SIZE
    OP_NIP OP_ROT OP_NUMEQUALVERIFY
  ` },
  { name: 'millerEvent', originalId: 1, body: `
    NUM BASE_FIELD OP_PUSHBYTES_1 0x1a OP_ROLL OP_DUP OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP OP_BIN2NUM OP_SWAP
    OP_DUP OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP OP_BIN2NUM OP_SWAP OP_0 OP_0 OP_PUSHBYTES_1 0x20 OP_PICK OP_1
    OP_GREATERTHANOREQUAL OP_IF OP_2 OP_PICK OP_PUSHBYTES_1 0x20 OP_SPLIT OP_OVER OP_BIN2NUM OP_4 OP_ROLL
    OP_DROP OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_FROMALTSTACK OP_FROMALTSTACK OP_DUP OP_5
    OP_ROLL OP_DROP OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_4 OP_PICK OP_PUSHBYTES_1 0x20 OP_SPLIT OP_OVER OP_BIN2NUM OP_5 OP_ROLL
    OP_DROP OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_DUP OP_7 OP_ROLL OP_DROP CALL sharedSequence19 OP_TOALTSTACK OP_SWAP
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_2DROP OP_2DROP
    OP_ENDIF OP_ROT OP_SIZE OP_NIP OP_0 OP_NUMEQUALVERIFY OP_1 OP_PUSHBYTES_1 0x20 OP_PICK OP_1 OP_NUMEQUAL
    OP_IF OP_8 OP_PICK OP_NIP OP_ENDIF OP_PUSHBYTES_1 0x20 OP_PICK OP_2 OP_NUMEQUAL OP_IF OP_9 OP_PICK OP_NIP
    OP_ENDIF OP_3 OP_ROLL OP_5 OP_ROLL OP_13 OP_ROLL OP_13 OP_ROLL OP_13 OP_ROLL OP_13 OP_ROLL NUM BASE_FIELD
    OP_2 OP_PICK OP_2 OP_PICK CALL sharedSequence3 OP_OVER OP_DUP OP_ADD OP_ROT OP_ADD OP_OVER OP_DUP OP_ADD
    OP_ROT OP_ADD OP_PUSHBYTES_1 0x40 OP_7 OP_PICK OP_8 OP_PICK OP_ADD OP_7 OP_PICK OP_8 OP_PICK OP_ADD CALL
    sharedSequence7 OP_8 OP_PICK OP_8 OP_PICK CALL sharedSequence3 OP_1 OP_ROT OP_PUSHBYTES_32
    0x21b0e9bc669cf61ecf39b03c8d7c1bf28f8f9e505ebe9914b8bfc6a9dc3a7520 CALL sharedSequence6 OP_1 OP_ROT
    OP_PUSHBYTES_32 0x764149911337e8adf84887af8ee1eef5ddf98acc090f86677efcd2b0103bc501 CALL sharedSequence6
    OP_12 OP_PICK OP_12 OP_PICK CALL sharedSequence3 OP_2 OP_10 OP_PICK OP_11 OP_PICK OP_ADD OP_3 OP_ROLL
    CALL sharedSequence6 OP_8 OP_PICK OP_MOD OP_2 OP_11 OP_PICK OP_12 OP_PICK OP_ADD OP_3 OP_ROLL CALL
    sharedSequence31 OP_2ROT OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL
    OP_9 OP_ROLL OP_9 OP_ROLL OP_PUSHBYTES_1 0x23 OP_PICK OP_PUSHBYTES_1 0x23 OP_PICK OP_PUSHBYTES_1 0x17
    OP_PICK OP_PUSHBYTES_1 0x17 OP_PICK OP_PUSHBYTES_1 0x17 OP_PICK OP_PUSHBYTES_1 0x17 OP_PICK OP_10 OP_ROLL
    OP_11 OP_ROLL OP_12 OP_ROLL OP_13 OP_ROLL OP_14 OP_ROLL OP_15 OP_ROLL OP_16 OP_PICK OP_PUSHBYTES_1 0x16
    OP_PICK CALL evaluateLineCoefficients OP_PUSHBYTES_1 0x20 OP_ROLL OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP
    OP_BIN2NUM OP_PUSHBYTES_1 0x13 OP_ROLL OP_PUSHBYTES_1 0x14 OP_ROLL OP_ADD OP_PUSHBYTES_1 0x14 OP_ROLL
    OP_ADD OP_PUSHBYTES_1 0x14 OP_ROLL OP_ADD OP_PUSHBYTES_1 0x14 OP_ROLL OP_ADD OP_PUSHBYTES_1 0x14 OP_ROLL
    OP_ADD OP_PUSHBYTES_1 0x14 OP_ROLL OP_ADD OP_PUSHBYTES_1 0x14 OP_ROLL OP_ADD OP_PUSHBYTES_1 0x11 OP_PICK
    OP_ADD OP_13 OP_PICK OP_MOD OP_DUP OP_NUMEQUALVERIFY OP_2 OP_PICK OP_MUL OP_12 OP_PICK OP_MOD
    OP_PUSHBYTES_1 0x19 OP_PICK OP_1 OP_GREATERTHANOREQUAL OP_IF OP_PUSHBYTES_1 0x15 OP_PICK OP_PUSHBYTES_1
    0x17 OP_PICK OP_PUSHBYTES_1 0x1b OP_PICK OP_1 OP_NUMEQUAL OP_IF OP_14 OP_PICK OP_PUSHBYTES_1 0x18 OP_PICK
    OP_SUB OP_15 OP_PICK OP_MOD OP_ROT OP_DROP OP_SWAP OP_14 OP_PICK OP_PUSHBYTES_1 0x19 OP_PICK OP_SUB OP_15
    OP_PICK OP_MOD OP_NIP OP_ENDIF OP_0 OP_0 OP_0 OP_0 OP_0 OP_0 OP_0 OP_0 OP_0 OP_0 OP_PUSHBYTES_1 0x25
    OP_PICK OP_1 OP_NUMEQUAL OP_IF OP_PUSHBYTES_1 0x14 OP_PICK OP_PUSHBYTES_1 0x16 OP_PICK OP_PUSHBYTES_1
    0x24 OP_PICK OP_PUSHBYTES_1 0x24 CALL sharedSequence23 OP_PUSHBYTES_1 0x40 OP_7 OP_PICK OP_7 OP_PICK OP_5
    OP_PICK OP_5 OP_PICK CALL sharedSequence11 OP_10 OP_PICK OP_10 OP_PICK OP_8 OP_PICK OP_8 OP_PICK OP_ROT
    OP_ADD OP_ROT OP_ROT OP_ADD OP_10 OP_PICK OP_10 OP_PICK OP_2OVER OP_SWAP CALL sharedSequence8 OP_14
    OP_ROLL OP_14 OP_ROLL OP_6 OP_PICK OP_8 OP_PICK CALL sharedSequence8 OP_1 OP_SWAP OP_ROT OP_7 CALL
    sharedSequence18 CALL sharedSequence28 CALL sharedSequence28 CALL sharedSequence28 CALL sharedSequence15
    OP_SWAP CALL sharedSequence16 OP_ELSE OP_PUSHBYTES_1 0x14 OP_PICK OP_PUSHBYTES_1 0x16 OP_PICK OP_12
    OP_PICK OP_14 CALL sharedSequence23 OP_OVER OP_6 OP_PICK OP_SUB OP_OVER OP_MOD OP_0 OP_NUMNOTEQUAL OP_3
    OP_PICK OP_8 OP_PICK OP_SUB OP_2 OP_PICK OP_MOD OP_0 OP_NUMNOTEQUAL OP_BOOLOR OP_VERIFY OP_PUSHBYTES_1
    0x40 OP_7 OP_PICK OP_7 OP_PICK OP_5 OP_PICK OP_5 OP_PICK CALL sharedSequence11 OP_PUSHBYTES_1 0x40 OP_11
    OP_PICK OP_11 OP_PICK OP_9 OP_PICK OP_9 OP_PICK CALL sharedSequence11 OP_10 OP_PICK OP_10 OP_PICK
    OP_2OVER OP_SWAP CALL sharedSequence8 OP_14 OP_ROLL OP_14 OP_ROLL OP_6 OP_PICK OP_8 OP_PICK OP_8 CALL
    sharedSequence18 CALL sharedSequence28 CALL sharedSequence28 CALL sharedSequence28 CALL sharedSequence15
    OP_SWAP CALL sharedSequence16 OP_ENDIF OP_PUSHBYTES_1 0x24 OP_PICK OP_PUSHBYTES_1 0x24 OP_PICK
    OP_PUSHBYTES_1 0x20 OP_PICK OP_PUSHBYTES_1 0x20 OP_PICK OP_PUSHBYTES_1 0x20 OP_PICK OP_PUSHBYTES_1 0x20
    OP_PICK OP_10 OP_PICK OP_12 OP_PICK OP_14 OP_PICK OP_16 OP_PICK OP_PUSHBYTES_1 0x12 OP_PICK
    OP_PUSHBYTES_1 0x14 OP_PICK OP_PUSHBYTES_1 0x18 OP_PICK OP_PUSHBYTES_1 0x25 OP_PICK CALL
    evaluateLineCoefficients OP_13 OP_ROLL OP_DROP CALL sharedSequence15 OP_SWAP OP_TOALTSTACK OP_SWAP
    OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP CALL sharedSequence16 OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_3 OP_PICK OP_PUSHBYTES_1 0x13 CALL sharedSequence29 CALL sharedSequence30
    OP_FROMALTSTACK OP_2 OP_PICK OP_PUSHBYTES_1 0x12 CALL sharedSequence29 OP_SWAP CALL sharedSequence16 CALL
    sharedSequence16 OP_OVER OP_PUSHBYTES_1 0x11 CALL sharedSequence34 OP_TOALTSTACK OP_SWAP CALL
    sharedSequence32 OP_FROMALTSTACK OP_DUP OP_16 CALL sharedSequence34 CALL sharedSequence32 OP_13 OP_PICK
    OP_PUSHBYTES_1 0x20 OP_SPLIT OP_OVER OP_BIN2NUM OP_15 OP_PICK OP_OVER OP_MUL OP_PUSHBYTES_1 0x1c OP_PICK
    OP_MOD OP_16 CALL sharedSequence34 CALL sharedSequence32 OP_OVER OP_SIZE OP_NIP OP_0 OP_NUMEQUALVERIFY
    OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_DROP OP_ENDIF OP_PUSHBYTES_1 0x19
    OP_ROLL OP_0 OP_NUMEQUAL OP_IF OP_OVER OP_SIZE OP_NIP OP_0 OP_NUMEQUALVERIFY OP_ENDIF OP_DUP OP_13
    OP_PICK OP_ADD OP_13 OP_ROLL OP_MOD OP_7 OP_ROLL OP_7 OP_ROLL OP_7 OP_ROLL OP_7 OP_ROLL OP_TOALTSTACK
    OP_TOALTSTACK OP_TOALTSTACK OP_TOALTSTACK OP_TOALTSTACK CALL sharedSequence22 OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
  ` },
  { name: 'sharedSequence3', originalId: 3, body: `
    OP_2DUP CALL sharedSequence4 NUM SQUARE_BIAS OP_2OVER OP_SWAP OP_SUB OP_ADD OP_2OVER OP_ADD CALL
    sharedSequence4 OP_OVER OP_ROT OP_ADD OP_2SWAP OP_2DROP
  ` },
  { name: 'sharedSequence4', originalId: 4, body: `
    OP_MUL NUM BASE_FIELD OP_MOD
  ` },
  { name: 'sharedSequence6', originalId: 6, body: `
    OP_SWAP OP_SUB OP_SWAP NUM BASE_FIELD OP_MUL OP_ADD
  ` },
  { name: 'sharedSequence7', originalId: 7, body: `
    OP_2 OP_PICK OP_SWAP OP_0 CALL sharedSequence6 OP_ROT OP_ROT OP_0 CALL sharedSequence6
  ` },
  { name: 'sharedSequence8', originalId: 8, body: `
    OP_2 OP_PICK OP_OVER CALL sharedSequence4 OP_4 OP_PICK OP_3 OP_PICK CALL sharedSequence4 OP_1 OP_OVER
    OP_3 OP_PICK CALL sharedSequence6 OP_2 OP_2SWAP OP_ADD OP_6 OP_ROLL OP_6 OP_ROLL OP_ADD OP_2ROT OP_ADD
    CALL sharedSequence4 CALL sharedSequence6
  ` },
  { name: 'evaluateLineCoefficients', originalId: 9, body: `
    OP_SWAP OP_6 OP_ROLL OP_8 OP_ROLL OP_MUL OP_7 OP_ROLL OP_8 OP_ROLL OP_MUL OP_ADD OP_5 OP_ROLL OP_7
    OP_ROLL OP_MUL OP_ADD OP_5 OP_ROLL OP_6 OP_ROLL OP_MUL OP_ADD OP_3 OP_ROLL OP_5 OP_ROLL OP_MUL OP_ADD
    OP_3 OP_ROLL OP_4 OP_ROLL OP_MUL OP_ADD OP_MUL OP_SWAP OP_MOD
  ` },
  { name: 'sharedSequence11', originalId: 11, body: `
    OP_4 OP_PICK OP_3 OP_ROLL OP_ROT CALL sharedSequence6 OP_2SWAP OP_3 OP_ROLL CALL sharedSequence6
  ` },
  { name: 'pairedEventFold', originalId: 14, body: `
    NUM BASE_FIELD OP_PUSHBYTES_2 0x8000 OP_PUSHBYTES_2 0x8000 OP_PUSHBYTES_1 0x40 OP_PUSHBYTES_1 0x40
    OP_PUSHBYTES_1 0x23 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_PUSHBYTES_1 0x40 OP_4 OP_ROLL OP_DROP OP_SWAP
    OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_FROMALTSTACK OP_FROMALTSTACK OP_PUSHBYTES_1 0x20 OP_ROT
    OP_DROP OP_SWAP OP_ENDIF OP_PUSHBYTES_1 0x24 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_PUSHBYTES_1 0x40 OP_3
    OP_ROLL OP_DROP OP_SWAP OP_TOALTSTACK OP_SWAP OP_FROMALTSTACK OP_PUSHBYTES_1 0x20 OP_NIP OP_ENDIF
    OP_PUSHBYTES_1 0x25 OP_ROLL OP_4 OP_ROLL OP_SPLIT OP_PUSHBYTES_1 0x26 OP_ROLL OP_4 OP_ROLL OP_SPLIT
    OP_ROT OP_5 OP_ROLL OP_SPLIT OP_ROT OP_5 OP_ROLL OP_SPLIT OP_ROT OP_PUSHBYTES_1 0x40 OP_SPLIT OP_SWAP
    OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SIZE OP_PUSHBYTES_1 0x20 OP_NUMEQUALVERIFY OP_REVERSEBYTES
    OP_BIN2NUM OP_8 OP_PICK OP_ADD OP_8 OP_PICK OP_MOD OP_SWAP OP_6 OP_ROLL OP_7 OP_ROLL OP_PUSHBYTES_1 0x27
    OP_ROLL CALL sharedSequence25 CALL sharedSequence25 CALL sharedSequence25 CALL sharedSequence25 CALL
    sharedSequence25 CALL sharedSequence25 OP_PUSHBYTES_1 0x27 OP_ROLL OP_PUSHBYTES_1 0x27 OP_ROLL
    OP_PUSHBYTES_1 0x27 OP_ROLL OP_PUSHBYTES_1 0x27 OP_ROLL OP_PUSHBYTES_1 0x27 OP_PICK OP_PUSHBYTES_1 0x27
    OP_PICK CALL millerEvent OP_9 OP_ROLL OP_10 OP_ROLL CALL sharedSequence26 CALL sharedSequence26 CALL
    sharedSequence26 CALL sharedSequence26 CALL sharedSequence26 CALL sharedSequence26 OP_PUSHBYTES_1 0x26
    OP_ROLL OP_PUSHBYTES_1 0x15 OP_ROLL OP_PUSHBYTES_1 0x16 OP_ROLL OP_PUSHBYTES_1 0x17 OP_ROLL
    OP_PUSHBYTES_1 0x18 OP_ROLL OP_PUSHBYTES_1 0x26 OP_ROLL OP_PUSHBYTES_1 0x26 OP_ROLL CALL millerEvent
    OP_14 OP_PICK OP_15 OP_ROLL OP_MUL OP_6 OP_ROLL OP_MUL OP_10 OP_PICK OP_MOD OP_DUP OP_MUL OP_5 OP_ROLL
    OP_MUL OP_9 OP_PICK OP_MOD OP_10 OP_PICK OP_10 OP_PICK OP_ADD OP_13 OP_PICK OP_ROT OP_MUL OP_ADD OP_9
    OP_PICK OP_MOD OP_11 OP_PICK OP_10 OP_PICK OP_ADD OP_13 OP_PICK OP_8 OP_PICK OP_MUL OP_ADD OP_10 OP_PICK
    OP_MOD OP_13 OP_PICK OP_16 OP_ROLL OP_MUL OP_11 OP_ROLL OP_MOD OP_14 OP_PICK OP_16 OP_ROLL OP_4
    OP_NUM2BIN OP_REVERSEBYTES OP_CAT OP_PUSHBYTES_4 0x00000020 OP_CAT OP_8 OP_ROLL OP_CAT OP_HASH256
    OP_2SWAP OP_3 OP_ROLL OP_8 OP_ROLL OP_4 OP_ROLL OP_8 OP_ROLL OP_8 OP_ROLL OP_8 OP_ROLL OP_8 OP_ROLL OP_9
    OP_ROLL OP_10 OP_ROLL OP_11 OP_ROLL OP_DROP OP_11 OP_ROLL OP_DROP OP_11 OP_ROLL OP_DROP OP_11 OP_ROLL
    OP_DROP
  ` },
  { name: 'sharedSequence15', originalId: 15, body: `
    OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP
    OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK
  ` },
  { name: 'sharedSequence16', originalId: 16, body: `
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK
  ` },
  { name: 'sharedSequence17', originalId: 17, body: `
    OP_PICK OP_PUSHBYTES_1 0x24 OP_PICK OP_PUSHBYTES_1 0x26 OP_PICK OP_PUSHBYTES_1 0x28 OP_PICK
    OP_PUSHBYTES_1 0x2a OP_PICK OP_PUSHBYTES_1 0x2c CALL sharedSequence36
  ` },
  { name: 'sharedSequence18', originalId: 18, body: `
    INVOKE_STACK OP_3 OP_SWAP OP_2SWAP OP_SWAP OP_4 OP_ROLL CALL sharedSequence11 OP_PUSHBYTES_1 0x40 OP_3
    OP_ROLL OP_4 OP_ROLL CALL sharedSequence7 OP_2ROT OP_14 OP_PICK OP_14 OP_PICK CALL sharedSequence3
    OP_PUSHBYTES_1 0x40 OP_14 OP_ROLL OP_PUSHBYTES_1 0x40 OP_12 OP_PICK OP_5 OP_ROLL CALL sharedSequence6
    CALL sharedSequence6 OP_8 OP_PICK OP_MOD OP_PUSHBYTES_1 0x40 OP_14 OP_ROLL OP_PUSHBYTES_1 0x40 OP_13
    OP_PICK OP_5 OP_ROLL CALL sharedSequence6 CALL sharedSequence31 OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL
    OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_10 OP_ROLL
    OP_DROP
  ` },
  { name: 'sharedSequence19', originalId: 19, body: `
    OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP
  ` },
  { name: 'sharedSequence20', originalId: 20, body: `
    OP_SWAP OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP OP_BIN2NUM OP_SWAP OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP
    OP_BIN2NUM
  ` },
  { name: 'sharedSequence21', originalId: 21, body: `
    OP_PICK OP_PUSHBYTES_1 0x19 OP_PICK OP_PUSHBYTES_1 0x1b OP_PICK OP_PUSHBYTES_1 0x1d OP_PICK
    OP_PUSHBYTES_1 0x1f OP_PICK
  ` },
  { name: 'sharedSequence22', originalId: 22, body: `
    OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP
  ` },
  { name: 'sharedSequence23', originalId: 23, body: `
    OP_PICK OP_PUSHBYTES_1 0x24 OP_PICK OP_PUSHBYTES_1 0x24 OP_PICK OP_PUSHBYTES_1 0x15 OP_PICK
    OP_PUSHBYTES_1 0x17 OP_PICK OP_PUSHBYTES_1 0x19 OP_PICK OP_PUSHBYTES_1 0x1b OP_PICK NUM BASE_FIELD
  ` },
  { name: 'sharedSequence24', originalId: 24, body: `
    OP_ADD OP_3 OP_PICK OP_5 OP_PICK OP_3 OP_ROLL OP_4 OP_ROLL
  ` },
  { name: 'sharedSequence25', originalId: 25, body: `
    OP_PUSHBYTES_1 0x27 OP_PICK OP_PUSHBYTES_1 0x27 OP_PICK OP_PUSHBYTES_1 0x27 OP_PICK
  ` },
  { name: 'sharedSequence26', originalId: 26, body: `
    OP_PUSHBYTES_1 0x26 OP_ROLL OP_PUSHBYTES_1 0x26 OP_ROLL OP_PUSHBYTES_1 0x26 OP_ROLL
  ` },
  { name: 'sharedSequence27', originalId: 27, body: `
    OP_PICK OP_PUSHBYTES_1 0x28 OP_PICK OP_PUSHBYTES_1 0x2a OP_PICK OP_PUSHBYTES_1 0x2c OP_PICK
    OP_PUSHBYTES_1 0x2e OP_PICK
  ` },
  { name: 'sharedSequence28', originalId: 28, body: `
    OP_12 OP_ROLL OP_12 OP_ROLL OP_12 OP_ROLL OP_2DROP OP_DROP OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL OP_9 OP_ROLL
  ` },
  { name: 'sharedSequence29', originalId: 29, body: `
    OP_ROLL OP_DROP CALL sharedSequence15 CALL sharedSequence15
  ` },
  { name: 'sharedSequence30', originalId: 30, body: `
    OP_SWAP OP_TOALTSTACK OP_SWAP CALL sharedSequence16 CALL sharedSequence16
  ` },
  { name: 'sharedSequence31', originalId: 31, body: `
    CALL sharedSequence6 OP_8 OP_PICK OP_MOD OP_1 OP_OVER OP_12 OP_ROLL CALL sharedSequence6 OP_1 OP_3
    OP_PICK OP_12 OP_ROLL CALL sharedSequence6 OP_14 OP_ROLL OP_14 OP_ROLL CALL sharedSequence8 OP_1 OP_12
    OP_ROLL OP_3 OP_ROLL CALL sharedSequence6 OP_10 OP_PICK OP_MOD OP_1 OP_12 OP_ROLL OP_3 OP_ROLL CALL
    sharedSequence6 OP_10 OP_ROLL OP_MOD
  ` },
  { name: 'sharedSequence32', originalId: 32, body: `
    OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP CALL sharedSequence16 OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
  ` },
  { name: 'sharedSequence33', originalId: 33, body: `
    CALL sharedSequence16 CALL sharedSequence16 OP_FROMALTSTACK OP_FROMALTSTACK
  ` },
  { name: 'sharedSequence34', originalId: 34, body: `
    OP_ROLL OP_DROP CALL sharedSequence15 CALL sharedSequence19
  ` },
  { name: 'sharedSequence35', originalId: 35, body: `
    CALL sharedSequence15 CALL sharedSequence15 CALL sharedSequence15
  ` },
  { name: 'sharedSequence36', originalId: 36, body: `
    OP_PICK CALL pairedEventFold OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10
    OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL
  ` },
];

export const main = `
    NUM BASE_FIELD OP_INPUTINDEX OP_DUP OP_3 OP_LESSTHAN OP_VERIFY OP_PUSHBYTES_5 0x2110012141 OP_OVER OP_1
    OP_NUMEQUAL OP_IF OP_PUSHBYTES_6 0x004208018400 OP_NIP OP_ENDIF OP_OVER OP_2 OP_NUMEQUAL OP_IF
    OP_PUSHBYTES_6 0x400402418800 OP_NIP OP_ENDIF OP_4 OP_2 OP_PICK OP_1 OP_NUMEQUAL OP_IF OP_DROP OP_14
    OP_ENDIF OP_2 OP_PICK OP_2 OP_NUMEQUAL OP_IF OP_PUSHBYTES_1 0x18 OP_NIP OP_ENDIF OP_10 OP_3 OP_PICK OP_1
    OP_NUMEQUAL OP_IF OP_DROP OP_10 OP_ENDIF OP_3 OP_PICK OP_2 OP_NUMEQUAL OP_IF OP_DROP OP_11 OP_ENDIF OP_0
    OP_4 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_PUSHBYTES_2 0xa003 OP_PUSHBYTES_2 0x4510 OP_0 CALL
    readBoundedInputSlice OP_NIP OP_ENDIF OP_4 OP_PICK OP_1 OP_NUMEQUAL OP_IF OP_PUSHBYTES_2 0x4003
    OP_PUSHBYTES_2 0xf710 OP_1 CALL readBoundedInputSlice OP_NIP OP_ENDIF OP_4 OP_PICK OP_2 OP_NUMEQUAL OP_IF
    OP_PUSHBYTES_2 0xa003 OP_PUSHBYTES_2 0x5d10 OP_2 CALL readBoundedInputSlice OP_NIP OP_ENDIF
    OP_PUSHBYTES_2 0xc001 OP_3 OP_3 CALL readBoundedInputSlice OP_0 OP_6 OP_PICK OP_0 OP_NUMEQUAL OP_IF
    OP_PUSHBYTES_2 0x2801 OP_3 OP_1 CALL readBoundedInputSlice OP_NIP OP_ENDIF OP_6 OP_PICK OP_1 OP_NUMEQUAL
    OP_IF OP_PUSHBYTES_2 0x2801 OP_3 OP_2 CALL readBoundedInputSlice OP_NIP OP_ENDIF OP_6 OP_PICK OP_2
    OP_NUMEQUAL OP_IF OP_PUSHBYTES_2 0x2801 OP_3 OP_4 CALL readBoundedInputSlice OP_NIP OP_ENDIF OP_2 OP_PICK
    OP_SIZE OP_NIP OP_0 OP_GREATERTHAN OP_VERIFY CALL sharedSequence20 CALL sharedSequence20 CALL
    sharedSequence20 CALL sharedSequence20 CALL sharedSequence20 CALL sharedSequence20 CALL sharedSequence20
    OP_SWAP OP_SIZE OP_NIP OP_0 OP_NUMEQUALVERIFY OP_PUSHBYTES_1 0x15 OP_ROLL OP_PUSHBYTES_1 0x28 OP_SPLIT
    OP_SWAP OP_BIN2NUM CALL sharedSequence20 CALL sharedSequence20 CALL sharedSequence20 CALL
    sharedSequence20 OP_SWAP OP_SIZE OP_NIP OP_0 OP_NUMEQUALVERIFY OP_8 OP_ROLL OP_PUSHBYTES_1 0x21
    OP_NUM2BIN OP_PUSHBYTES_1 0x20 OP_SPLIT OP_DROP OP_PUSHBYTES_1 0x1d OP_PICK OP_9 OP_SUB OP_PUSHBYTES_1
    0x16 OP_PICK OP_PUSHBYTES_1 0x1f OP_PICK OP_MOD OP_DUP OP_PUSHBYTES_1 0x18 OP_PICK OP_MUL OP_PUSHBYTES_1
    0x20 OP_PICK OP_MOD OP_PUSHBYTES_1 0x18 OP_PICK OP_MUL OP_PUSHBYTES_1 0x20 OP_PICK OP_MOD OP_DUP
    OP_PUSHBYTES_1 0x19 OP_PICK OP_MUL OP_PUSHBYTES_1 0x21 OP_PICK OP_MOD OP_PUSHBYTES_1 0x19 OP_PICK OP_MUL
    OP_PUSHBYTES_1 0x21 OP_PICK OP_MOD OP_PUSHBYTES_1 0x19 OP_PICK OP_MUL OP_PUSHBYTES_1 0x21 OP_PICK OP_MOD
    OP_DUP OP_PUSHBYTES_1 0x1a OP_PICK OP_MUL OP_PUSHBYTES_1 0x22 OP_PICK OP_MOD OP_DUP OP_PUSHBYTES_1 0x1b
    OP_PICK OP_MUL OP_PUSHBYTES_1 0x23 OP_PICK OP_MOD OP_PUSHBYTES_1 0x1b OP_ROLL OP_MUL OP_PUSHBYTES_1 0x22
    OP_PICK OP_MOD OP_5 OP_PICK OP_3 OP_ROLL OP_ADD OP_PUSHBYTES_1 0x22 OP_PICK OP_MOD OP_5 OP_PICK OP_5
    OP_PICK OP_MUL OP_3 OP_ROLL OP_ADD OP_PUSHBYTES_1 0x22 OP_PICK OP_MOD OP_3 OP_PICK OP_6 OP_ROLL OP_5
    OP_ROLL OP_MUL OP_4 OP_ROLL OP_ADD OP_PUSHBYTES_1 0x21 OP_PICK OP_MOD OP_PUSHBYTES_1 0x18 OP_PICK
    OP_PUSHBYTES_1 0x19 OP_ROLL OP_5 OP_PICK OP_MUL OP_PUSHBYTES_1 0x22 OP_PICK OP_MOD OP_PUSHBYTES_1 0x1a
    OP_PICK OP_7 OP_PICK OP_MUL OP_PUSHBYTES_1 0x23 OP_PICK OP_MOD OP_PUSHBYTES_1 0x1b OP_ROLL OP_6 OP_PICK
    OP_MUL OP_PUSHBYTES_1 0x23 OP_PICK OP_MOD OP_PUSHBYTES_1 0x1a OP_PICK OP_PUSHBYTES_1 0x1b OP_ROLL OP_9
    OP_PICK OP_MUL OP_PUSHBYTES_1 0x24 OP_PICK OP_MOD OP_PUSHBYTES_1 0x1c OP_PICK OP_11 OP_PICK OP_MUL
    OP_PUSHBYTES_1 0x25 OP_PICK OP_MOD OP_PUSHBYTES_1 0x1d OP_ROLL OP_10 OP_PICK OP_MUL OP_PUSHBYTES_1 0x25
    OP_PICK OP_MOD OP_PUSHBYTES_1 0x1c OP_PICK OP_PUSHBYTES_1 0x1d OP_ROLL OP_13 OP_ROLL OP_MUL
    OP_PUSHBYTES_1 0x25 OP_PICK OP_MOD OP_PUSHBYTES_1 0x1d OP_PICK OP_14 OP_ROLL OP_MUL OP_PUSHBYTES_1 0x25
    OP_PICK OP_MOD OP_PUSHBYTES_1 0x1d OP_ROLL OP_14 OP_ROLL OP_MUL OP_PUSHBYTES_1 0x24 OP_PICK OP_MOD
    OP_PUSHBYTES_1 0x25 OP_ROLL OP_PUSHBYTES_1 0x20 OP_ROLL OP_PUSHBYTES_1 0x14 OP_ROLL OP_PUSHBYTES_1 0x14
    OP_ROLL OP_PUSHBYTES_1 0x14 OP_ROLL OP_PUSHBYTES_1 0x14 OP_ROLL OP_0 OP_PUSHBYTES_1 0x25 OP_PICK OP_0
    OP_NUMEQUAL OP_IF OP_DROP OP_1 OP_ENDIF OP_PUSHBYTES_1 0x25 OP_ROLL OP_0 OP_NUMEQUAL OP_IF OP_PUSHBYTES_1
    0x24 OP_PICK OP_4 OP_MOD OP_DUP OP_2 OP_LESSTHANOREQUAL OP_VERIFY OP_PUSHBYTES_2 0x8000 OP_PUSHBYTES_1
    0x40 OP_2 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_PUSHBYTES_1 0x40 OP_ROT OP_DROP OP_SWAP OP_PUSHBYTES_1 0x20
    OP_NIP OP_ENDIF OP_9 OP_PICK OP_2 OP_PICK OP_SPLIT OP_10 OP_PICK OP_3 OP_PICK OP_SPLIT OP_2 OP_PICK
    OP_PUSHBYTES_1 0x40 OP_SPLIT OP_OVER OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SIZE OP_PUSHBYTES_1
    0x20 OP_NUMEQUALVERIFY OP_DUP OP_REVERSEBYTES OP_DUP OP_BIN2NUM OP_PUSHBYTES_1 0x32 OP_PICK OP_ADD
    OP_PUSHBYTES_1 0x32 OP_PICK OP_MOD OP_3 OP_PICK OP_5 OP_PICK OP_PUSHBYTES_1 0x15 CALL sharedSequence29
    OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK CALL sharedSequence30 OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_7 OP_PICK OP_PUSHBYTES_1 0x14 CALL sharedSequence29 OP_SWAP OP_TOALTSTACK CALL
    sharedSequence30 OP_FROMALTSTACK OP_FROMALTSTACK OP_8 OP_PICK OP_11 OP_PICK OP_15 OP_PICK OP_PUSHBYTES_1
    0x24 OP_PICK OP_PUSHBYTES_1 0x26 OP_PICK OP_PUSHBYTES_1 0x2f OP_PICK OP_PUSHBYTES_1 0x31 OP_PICK
    OP_PUSHBYTES_1 0x33 OP_PICK OP_PUSHBYTES_1 0x35 OP_PICK OP_PUSHBYTES_1 0x1e OP_PICK OP_PUSHBYTES_1 0x20
    OP_PICK OP_PUSHBYTES_1 0x22 OP_PICK OP_PUSHBYTES_1 0x24 OP_PICK OP_PUSHBYTES_1 0x26 CALL sharedSequence27
    OP_PUSHBYTES_1 0x30 OP_PICK OP_PUSHBYTES_1 0x32 OP_PICK OP_PUSHBYTES_1 0x34 OP_PICK OP_PUSHBYTES_1 0x24
    OP_PICK OP_PUSHBYTES_1 0x26 OP_PICK OP_PUSHBYTES_1 0x28 OP_PICK OP_PUSHBYTES_1 0x2a OP_PICK
    OP_PUSHBYTES_1 0x41 OP_PICK OP_PUSHBYTES_1 0x43 OP_PICK CALL millerEvent OP_PUSHBYTES_1 0x29 OP_PICK
    OP_PUSHBYTES_1 0x2a OP_PICK OP_MUL OP_5 OP_PICK OP_MUL OP_PUSHBYTES_1 0x39 OP_PICK OP_MOD OP_PUSHBYTES_1
    0x2d OP_PICK OP_PUSHBYTES_1 0x3a OP_PICK OP_ADD OP_PUSHBYTES_1 0x2c OP_PICK OP_2 OP_PICK OP_MUL OP_ADD
    OP_PUSHBYTES_1 0x3a OP_PICK OP_MOD OP_PUSHBYTES_1 0x2e CALL sharedSequence29 CALL sharedSequence35 CALL
    sharedSequence19 CALL sharedSequence16 CALL sharedSequence16 CALL sharedSequence16 CALL sharedSequence33
    OP_FROMALTSTACK OP_FROMALTSTACK OP_PUSHBYTES_1 0x2c OP_PICK OP_PUSHBYTES_1 0x3a OP_PICK OP_ADD
    OP_PUSHBYTES_1 0x2c OP_PICK OP_9 OP_PICK OP_MUL OP_ADD OP_PUSHBYTES_1 0x3a OP_PICK OP_MOD OP_PUSHBYTES_1
    0x2d CALL sharedSequence29 CALL sharedSequence35 OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK CALL
    sharedSequence30 CALL sharedSequence16 CALL sharedSequence33 OP_FROMALTSTACK OP_PUSHBYTES_1 0x2b OP_PICK
    OP_PUSHBYTES_1 0x35 OP_PICK OP_MUL OP_PUSHBYTES_1 0x3a OP_PICK OP_MOD OP_PUSHBYTES_1 0x2c CALL
    sharedSequence29 CALL sharedSequence35 OP_SWAP OP_TOALTSTACK CALL sharedSequence30 CALL sharedSequence16
    CALL sharedSequence33 OP_7 OP_PICK OP_PUSHBYTES_1 0x2b CALL sharedSequence29 CALL sharedSequence35 CALL
    sharedSequence30 CALL sharedSequence16 CALL sharedSequence16 CALL sharedSequence16 OP_FROMALTSTACK
    OP_PUSHBYTES_1 0x29 OP_PICK OP_3 OP_4 OP_NUM2BIN OP_REVERSEBYTES OP_CAT OP_PUSHBYTES_4 0x00000020 OP_CAT
    OP_7 OP_PICK OP_CAT OP_HASH256 OP_PUSHBYTES_1 0x2a CALL sharedSequence29 CALL sharedSequence35 OP_SWAP
    CALL sharedSequence16 CALL sharedSequence16 CALL sharedSequence16 CALL sharedSequence16 CALL
    sharedSequence16 OP_4 OP_PICK OP_PUSHBYTES_1 0x19 CALL sharedSequence29 CALL sharedSequence19
    OP_TOALTSTACK OP_SWAP OP_TOALTSTACK CALL sharedSequence30 OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_3 OP_PICK OP_PUSHBYTES_1 0x18 CALL
    sharedSequence29 CALL sharedSequence19 OP_TOALTSTACK CALL sharedSequence30 OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_2 OP_PICK
    OP_PUSHBYTES_1 0x17 CALL sharedSequence29 CALL sharedSequence19 OP_TOALTSTACK OP_SWAP CALL
    sharedSequence33 OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_OVER OP_PUSHBYTES_1 0x16 CALL
    sharedSequence29 CALL sharedSequence19 CALL sharedSequence33 OP_FROMALTSTACK OP_FROMALTSTACK CALL
    sharedSequence22 OP_ENDIF OP_PUSHBYTES_1 0x24 OP_PICK OP_2 OP_2 OP_PICK OP_0 OP_ADD OP_MUL OP_RSHIFTNUM
    OP_4 OP_MOD OP_PUSHBYTES_1 0x25 OP_PICK OP_2 OP_3 OP_PICK OP_0 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4
    OP_MOD OP_PUSHBYTES_1 0x25 OP_PICK OP_0 OP_ADD OP_8 OP_PICK OP_10 OP_PICK OP_3 OP_ROLL OP_4 OP_ROLL
    OP_PUSHBYTES_1 0x18 OP_PICK OP_PUSHBYTES_1 0x1a OP_PICK OP_PUSHBYTES_1 0x23 OP_PICK OP_PUSHBYTES_1 0x25
    OP_PICK OP_PUSHBYTES_1 0x27 OP_PICK OP_PUSHBYTES_1 0x29 OP_PICK OP_PUSHBYTES_1 0x12 OP_PICK
    OP_PUSHBYTES_1 0x14 OP_PICK OP_PUSHBYTES_1 0x16 OP_PICK OP_PUSHBYTES_1 0x18 OP_PICK OP_PUSHBYTES_1 0x1a
    OP_PICK OP_PUSHBYTES_1 0x1c OP_PICK OP_PUSHBYTES_1 0x1e OP_PICK OP_PUSHBYTES_1 0x20 OP_PICK
    OP_PUSHBYTES_1 0x22 OP_PICK OP_PUSHBYTES_1 0x24 OP_PICK OP_PUSHBYTES_1 0x26 OP_PICK OP_PUSHBYTES_1 0x28
    OP_PICK OP_PUSHBYTES_1 0x18 OP_PICK OP_PUSHBYTES_1 0x1a OP_PICK OP_PUSHBYTES_1 0x1c OP_PICK
    OP_PUSHBYTES_1 0x1e OP_PICK OP_PUSHBYTES_1 0x35 OP_PICK OP_PUSHBYTES_1 0x37 OP_PICK OP_PUSHBYTES_1 0x3d
    OP_PICK OP_PUSHBYTES_1 0x33 OP_PICK OP_PUSHBYTES_1 0x35 OP_PICK OP_PUSHBYTES_1 0x37 OP_PICK
    OP_PUSHBYTES_1 0x39 OP_PICK OP_PUSHBYTES_1 0x3b CALL sharedSequence36 OP_PUSHBYTES_1 0x2f OP_PICK OP_2
    OP_13 OP_PICK OP_2 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x30 OP_PICK OP_2 OP_14 OP_PICK
    OP_2 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x30 OP_PICK OP_1ADD OP_3 OP_PICK OP_5
    OP_PICK OP_3 OP_ROLL OP_4 OP_ROLL OP_PUSHBYTES_1 0x23 OP_PICK OP_PUSHBYTES_1 0x25 OP_PICK OP_PUSHBYTES_1
    0x2e OP_PICK OP_PUSHBYTES_1 0x30 OP_PICK OP_PUSHBYTES_1 0x32 OP_PICK OP_PUSHBYTES_1 0x34 OP_PICK
    OP_PUSHBYTES_1 0x1d OP_PICK OP_PUSHBYTES_1 0x1f OP_PICK OP_PUSHBYTES_1 0x21 OP_PICK OP_PUSHBYTES_1 0x23
    OP_PICK OP_PUSHBYTES_1 0x25 OP_PICK OP_PUSHBYTES_1 0x27 OP_PICK OP_PUSHBYTES_1 0x29 OP_PICK
    OP_PUSHBYTES_1 0x2b OP_PICK OP_PUSHBYTES_1 0x2d OP_PICK OP_PUSHBYTES_1 0x2f OP_PICK OP_PUSHBYTES_1 0x31
    OP_PICK OP_PUSHBYTES_1 0x33 CALL sharedSequence21 OP_PUSHBYTES_1 0x40 OP_PICK OP_PUSHBYTES_1 0x42 OP_PICK
    OP_PUSHBYTES_1 0x48 CALL sharedSequence17 OP_PUSHBYTES_1 0x3a OP_PICK OP_2 OP_PUSHBYTES_1 0x18 OP_PICK
    OP_4 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x3b OP_PICK OP_2 OP_PUSHBYTES_1 0x19 OP_PICK
    OP_4 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x3b OP_PICK OP_2 CALL
    sharedSequence24 OP_PUSHBYTES_1 0x2e OP_PICK OP_PUSHBYTES_1 0x30 OP_PICK OP_PUSHBYTES_1 0x39 OP_PICK
    OP_PUSHBYTES_1 0x3b OP_PICK OP_PUSHBYTES_1 0x3d OP_PICK OP_PUSHBYTES_1 0x3f CALL sharedSequence27
    OP_PUSHBYTES_1 0x30 OP_PICK OP_PUSHBYTES_1 0x32 OP_PICK OP_PUSHBYTES_1 0x34 OP_PICK OP_PUSHBYTES_1 0x36
    OP_PICK OP_PUSHBYTES_1 0x38 OP_PICK OP_PUSHBYTES_1 0x3a OP_PICK OP_PUSHBYTES_1 0x3c OP_PICK
    OP_PUSHBYTES_1 0x3e CALL sharedSequence21 OP_PUSHBYTES_1 0x4b OP_PICK OP_PUSHBYTES_1 0x4d OP_PICK
    OP_PUSHBYTES_1 0x53 CALL sharedSequence17 OP_PUSHBYTES_1 0x45 OP_PICK OP_2 OP_PUSHBYTES_1 0x23 OP_PICK
    OP_6 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x46 OP_PICK OP_2 OP_PUSHBYTES_1 0x24 OP_PICK
    OP_6 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x46 OP_PICK OP_3 CALL
    sharedSequence24 OP_PUSHBYTES_1 0x39 OP_PICK OP_PUSHBYTES_1 0x3b OP_PICK OP_PUSHBYTES_1 0x44 OP_PICK
    OP_PUSHBYTES_1 0x46 OP_PICK OP_PUSHBYTES_1 0x48 OP_PICK OP_PUSHBYTES_1 0x4a OP_PICK OP_PUSHBYTES_1 0x33
    OP_PICK OP_PUSHBYTES_1 0x35 OP_PICK OP_PUSHBYTES_1 0x37 OP_PICK OP_PUSHBYTES_1 0x39 OP_PICK
    OP_PUSHBYTES_1 0x3b OP_PICK OP_PUSHBYTES_1 0x3d OP_PICK OP_PUSHBYTES_1 0x3f OP_PICK OP_PUSHBYTES_1 0x41
    OP_PICK OP_PUSHBYTES_1 0x43 OP_PICK OP_PUSHBYTES_1 0x45 OP_PICK OP_PUSHBYTES_1 0x47 OP_PICK
    OP_PUSHBYTES_1 0x49 CALL sharedSequence21 OP_PUSHBYTES_1 0x56 OP_PICK OP_PUSHBYTES_1 0x58 OP_PICK
    OP_PUSHBYTES_1 0x5e CALL sharedSequence17 OP_PUSHBYTES_1 0x50 OP_PICK OP_2 OP_PUSHBYTES_1 0x2e OP_PICK
    OP_8 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x51 OP_PICK OP_2 OP_PUSHBYTES_1 0x2f OP_PICK
    OP_8 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x51 OP_PICK OP_4 CALL
    sharedSequence24 OP_PUSHBYTES_1 0x44 OP_PICK OP_PUSHBYTES_1 0x46 OP_PICK OP_PUSHBYTES_1 0x4f OP_PICK
    OP_PUSHBYTES_1 0x51 OP_PICK OP_PUSHBYTES_1 0x53 OP_PICK OP_PUSHBYTES_1 0x55 OP_PICK OP_PUSHBYTES_1 0x3e
    OP_PICK OP_PUSHBYTES_1 0x40 OP_PICK OP_PUSHBYTES_1 0x42 OP_PICK OP_PUSHBYTES_1 0x44 OP_PICK
    OP_PUSHBYTES_1 0x46 OP_PICK OP_PUSHBYTES_1 0x48 OP_PICK OP_PUSHBYTES_1 0x4a OP_PICK OP_PUSHBYTES_1 0x4c
    OP_PICK OP_PUSHBYTES_1 0x4e OP_PICK OP_PUSHBYTES_1 0x50 OP_PICK OP_PUSHBYTES_1 0x52 OP_PICK
    OP_PUSHBYTES_1 0x54 CALL sharedSequence21 OP_PUSHBYTES_1 0x61 OP_PICK OP_PUSHBYTES_1 0x63 OP_PICK
    OP_PUSHBYTES_1 0x69 CALL sharedSequence17 OP_PUSHBYTES_1 0x5b OP_PICK OP_2 OP_PUSHBYTES_1 0x39 OP_PICK
    OP_10 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x5c OP_PICK OP_2 OP_PUSHBYTES_1 0x3a OP_PICK
    OP_10 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x5c OP_PICK OP_5 CALL
    sharedSequence24 OP_PUSHBYTES_1 0x4f OP_PICK OP_PUSHBYTES_1 0x51 OP_PICK OP_PUSHBYTES_1 0x5a OP_PICK
    OP_PUSHBYTES_1 0x5c OP_PICK OP_PUSHBYTES_1 0x5e OP_PICK OP_PUSHBYTES_1 0x60 OP_PICK OP_PUSHBYTES_1 0x49
    OP_PICK OP_PUSHBYTES_1 0x4b OP_PICK OP_PUSHBYTES_1 0x4d OP_PICK OP_PUSHBYTES_1 0x4f OP_PICK
    OP_PUSHBYTES_1 0x51 OP_PICK OP_PUSHBYTES_1 0x53 OP_PICK OP_PUSHBYTES_1 0x55 OP_PICK OP_PUSHBYTES_1 0x57
    OP_PICK OP_PUSHBYTES_1 0x59 OP_PICK OP_PUSHBYTES_1 0x5b OP_PICK OP_PUSHBYTES_1 0x5d OP_PICK
    OP_PUSHBYTES_1 0x5f CALL sharedSequence21 OP_PUSHBYTES_1 0x6c OP_PICK OP_PUSHBYTES_1 0x6e OP_PICK
    OP_PUSHBYTES_1 0x74 CALL sharedSequence17 OP_PUSHBYTES_1 0x66 OP_PICK OP_2 OP_PUSHBYTES_1 0x44 OP_PICK
    OP_12 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x67 OP_PICK OP_2 OP_PUSHBYTES_1 0x45 OP_PICK
    OP_12 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x67 OP_PICK OP_6 CALL
    sharedSequence24 OP_PUSHBYTES_1 0x5a OP_PICK OP_PUSHBYTES_1 0x5c OP_PICK OP_PUSHBYTES_1 0x65 OP_PICK
    OP_PUSHBYTES_1 0x67 OP_PICK OP_PUSHBYTES_1 0x69 OP_PICK OP_PUSHBYTES_1 0x6b OP_PICK OP_PUSHBYTES_1 0x54
    OP_PICK OP_PUSHBYTES_1 0x56 OP_PICK OP_PUSHBYTES_1 0x58 OP_PICK OP_PUSHBYTES_1 0x5a OP_PICK
    OP_PUSHBYTES_1 0x5c OP_PICK OP_PUSHBYTES_1 0x5e OP_PICK OP_PUSHBYTES_1 0x60 OP_PICK OP_PUSHBYTES_1 0x62
    OP_PICK OP_PUSHBYTES_1 0x64 OP_PICK OP_PUSHBYTES_1 0x66 OP_PICK OP_PUSHBYTES_1 0x68 OP_PICK
    OP_PUSHBYTES_1 0x6a CALL sharedSequence21 OP_PUSHBYTES_1 0x77 OP_PICK OP_PUSHBYTES_1 0x79 OP_PICK
    OP_PUSHBYTES_1 0x7f CALL sharedSequence17 OP_PUSHBYTES_1 0x71 OP_PICK OP_2 OP_PUSHBYTES_1 0x4f OP_PICK
    OP_14 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x72 OP_PICK OP_2 OP_PUSHBYTES_1 0x50 OP_PICK
    OP_14 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x72 OP_PICK OP_7 CALL
    sharedSequence24 OP_PUSHBYTES_1 0x65 OP_PICK OP_PUSHBYTES_1 0x67 OP_PICK OP_PUSHBYTES_1 0x70 OP_PICK
    OP_PUSHBYTES_1 0x72 OP_PICK OP_PUSHBYTES_1 0x74 OP_PICK OP_PUSHBYTES_1 0x76 OP_PICK OP_PUSHBYTES_1 0x5f
    OP_PICK OP_PUSHBYTES_1 0x61 OP_PICK OP_PUSHBYTES_1 0x63 OP_PICK OP_PUSHBYTES_1 0x65 OP_PICK
    OP_PUSHBYTES_1 0x67 OP_PICK OP_PUSHBYTES_1 0x69 OP_PICK OP_PUSHBYTES_1 0x6b OP_PICK OP_PUSHBYTES_1 0x6d
    OP_PICK OP_PUSHBYTES_1 0x6f OP_PICK OP_PUSHBYTES_1 0x71 OP_PICK OP_PUSHBYTES_1 0x73 OP_PICK
    OP_PUSHBYTES_1 0x75 CALL sharedSequence21 OP_PUSHBYTES_2 0x8200 OP_PICK OP_PUSHBYTES_2 0x8400 OP_PICK
    OP_PUSHBYTES_2 0x8a00 CALL sharedSequence17 OP_PUSHBYTES_1 0x7c OP_PICK OP_2 OP_PUSHBYTES_1 0x5a OP_PICK
    OP_16 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x7d OP_PICK OP_2 OP_PUSHBYTES_1 0x5b OP_PICK
    OP_16 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x7d OP_PICK OP_8 CALL
    sharedSequence24 OP_PUSHBYTES_1 0x70 OP_PICK OP_PUSHBYTES_1 0x72 OP_PICK OP_PUSHBYTES_1 0x7b OP_PICK
    OP_PUSHBYTES_1 0x7d OP_PICK OP_PUSHBYTES_1 0x7f OP_PICK OP_PUSHBYTES_2 0x8100 OP_PICK OP_PUSHBYTES_1 0x6a
    OP_PICK OP_PUSHBYTES_1 0x6c OP_PICK OP_PUSHBYTES_1 0x6e OP_PICK OP_PUSHBYTES_1 0x70 OP_PICK
    OP_PUSHBYTES_1 0x72 OP_PICK OP_PUSHBYTES_1 0x74 OP_PICK OP_PUSHBYTES_1 0x76 OP_PICK OP_PUSHBYTES_1 0x78
    OP_PICK OP_PUSHBYTES_1 0x7a OP_PICK OP_PUSHBYTES_1 0x7c OP_PICK OP_PUSHBYTES_1 0x7e OP_PICK
    OP_PUSHBYTES_2 0x8000 CALL sharedSequence21 OP_PUSHBYTES_2 0x8d00 OP_PICK OP_PUSHBYTES_2 0x8f00 OP_PICK
    OP_PUSHBYTES_2 0x9500 CALL sharedSequence17 OP_PUSHBYTES_2 0x8700 OP_PICK OP_2 OP_PUSHBYTES_1 0x65
    OP_PICK OP_PUSHBYTES_1 0x12 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_2 0x8800 OP_ROLL OP_2
    OP_PUSHBYTES_1 0x66 OP_ROLL OP_PUSHBYTES_1 0x12 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD
    OP_PUSHBYTES_2 0x8700 OP_PICK OP_9 CALL sharedSequence24 OP_PUSHBYTES_1 0x7a OP_PICK OP_PUSHBYTES_1 0x7c
    OP_PICK OP_PUSHBYTES_2 0x8500 OP_PICK OP_PUSHBYTES_2 0x8700 OP_PICK OP_PUSHBYTES_2 0x8900 OP_PICK
    OP_PUSHBYTES_2 0x8b00 OP_PICK OP_PUSHBYTES_1 0x74 OP_PICK OP_PUSHBYTES_1 0x76 OP_PICK OP_PUSHBYTES_1 0x78
    OP_PICK OP_PUSHBYTES_1 0x7a OP_PICK OP_PUSHBYTES_1 0x7c OP_PICK OP_PUSHBYTES_1 0x7e OP_PICK
    OP_PUSHBYTES_2 0x8000 OP_PICK OP_PUSHBYTES_2 0x8200 OP_PICK OP_PUSHBYTES_2 0x8400 OP_PICK OP_PUSHBYTES_2
    0x8600 OP_PICK OP_PUSHBYTES_2 0x8800 OP_PICK OP_PUSHBYTES_2 0x8a00 CALL sharedSequence21 OP_PUSHBYTES_2
    0x9700 OP_PICK OP_PUSHBYTES_2 0x9900 OP_PICK OP_PUSHBYTES_2 0x9f00 CALL sharedSequence17 OP_PUSHBYTES_2
    0x8f00 OP_ROLL OP_10 OP_GREATERTHAN OP_IF OP_0 OP_0 OP_PUSHBYTES_2 0x9100 OP_PICK OP_10 OP_ADD OP_3
    OP_PICK OP_5 OP_PICK OP_3 OP_PICK OP_5 OP_PICK OP_PUSHBYTES_2 0x8700 OP_PICK OP_PUSHBYTES_2 0x8900
    OP_PICK OP_PUSHBYTES_2 0x9200 OP_PICK OP_PUSHBYTES_2 0x9400 OP_PICK OP_PUSHBYTES_2 0x9600 OP_PICK
    OP_PUSHBYTES_2 0x9800 OP_PICK OP_PUSHBYTES_2 0x8100 OP_PICK OP_PUSHBYTES_2 0x8300 OP_PICK OP_PUSHBYTES_2
    0x8500 OP_PICK OP_PUSHBYTES_2 0x8700 OP_PICK OP_PUSHBYTES_2 0x8900 OP_PICK OP_PUSHBYTES_2 0x8b00 OP_PICK
    OP_PUSHBYTES_2 0x8d00 OP_PICK OP_PUSHBYTES_2 0x8f00 OP_PICK OP_PUSHBYTES_2 0x9100 OP_PICK OP_PUSHBYTES_2
    0x9300 OP_PICK OP_PUSHBYTES_2 0x9500 OP_PICK OP_PUSHBYTES_2 0x9700 OP_PICK OP_PUSHBYTES_1 0x1b OP_PICK
    OP_PUSHBYTES_1 0x1d OP_PICK OP_PUSHBYTES_1 0x1f OP_PICK OP_PUSHBYTES_1 0x21 OP_PICK OP_PUSHBYTES_2 0xa400
    OP_PICK OP_PUSHBYTES_2 0xa600 OP_PICK OP_PUSHBYTES_2 0xac00 OP_PICK OP_PUSHBYTES_1 0x26 CALL
    sharedSequence27 CALL pairedEventFold OP_10 OP_PICK OP_PUSHBYTES_1 0x18 CALL sharedSequence29 CALL
    sharedSequence19 OP_TOALTSTACK CALL sharedSequence30 OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_9 OP_PICK OP_PUSHBYTES_1 0x17 CALL sharedSequence29
    CALL sharedSequence19 OP_TOALTSTACK OP_SWAP CALL sharedSequence33 OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_8 OP_PICK OP_PUSHBYTES_1 0x16 CALL sharedSequence29 CALL sharedSequence19 CALL
    sharedSequence33 OP_FROMALTSTACK OP_FROMALTSTACK OP_7 OP_PICK OP_PUSHBYTES_1 0x15 CALL sharedSequence29
    OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK CALL sharedSequence30 OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_6 OP_PICK OP_PUSHBYTES_1 0x14 CALL sharedSequence29 OP_SWAP OP_TOALTSTACK CALL
    sharedSequence30 OP_FROMALTSTACK OP_FROMALTSTACK OP_5 OP_PICK OP_PUSHBYTES_1 0x13 CALL sharedSequence29
    CALL sharedSequence30 OP_FROMALTSTACK OP_4 OP_PICK OP_PUSHBYTES_1 0x12 CALL sharedSequence29 OP_SWAP CALL
    sharedSequence16 CALL sharedSequence16 OP_3 OP_PICK OP_PUSHBYTES_1 0x11 CALL sharedSequence34
    OP_TOALTSTACK OP_SWAP CALL sharedSequence32 OP_FROMALTSTACK OP_2 OP_PICK OP_16 CALL sharedSequence34 CALL
    sharedSequence32 OP_OVER OP_15 CALL sharedSequence34 OP_TOALTSTACK OP_SWAP CALL sharedSequence16
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_DUP OP_14 CALL
    sharedSequence34 CALL sharedSequence16 OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_DROP OP_ENDIF OP_SWAP OP_SIZE OP_NIP OP_0
    OP_NUMEQUAL OP_SWAP OP_SIZE OP_NIP OP_0 OP_NUMEQUAL OP_BOOLAND OP_VERIFY OP_4 OP_ROLL OP_PUSHBYTES_1 0x00
    OP_CAT OP_BIN2NUM OP_PUSHBYTES_1 0x28 OP_NUM2BIN OP_8 OP_ROLL OP_PUSHBYTES_2 0x8e00 OP_PICK OP_MOD
    OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_CAT OP_7 OP_ROLL OP_PUSHBYTES_2 0x8d00 OP_PICK OP_MOD OP_PUSHBYTES_1
    0x20 OP_NUM2BIN OP_7 OP_ROLL OP_PUSHBYTES_2 0x8d00 OP_PICK OP_MOD OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_CAT
    OP_CAT OP_5 OP_ROLL OP_PUSHBYTES_2 0x8b00 OP_PICK OP_MOD OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_5 OP_ROLL
    OP_PUSHBYTES_2 0x8b00 OP_PICK OP_MOD OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_CAT OP_4 OP_ROLL OP_PUSHBYTES_2
    0x8a00 OP_PICK OP_MOD OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_4 OP_ROLL OP_PUSHBYTES_2 0x8a00 OP_PICK OP_MOD
    OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_4 OP_ROLL OP_PUSHBYTES_2 0x8a00 OP_ROLL OP_MOD OP_PUSHBYTES_1 0x20
    OP_NUM2BIN OP_CAT OP_CAT OP_CAT OP_CAT OP_PUSHBYTES_2 0x8400 OP_ROLL OP_EQUALVERIFY CALL sharedSequence22
    CALL sharedSequence22 CALL sharedSequence22 CALL sharedSequence22 CALL sharedSequence22 CALL
    sharedSequence22 OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_1
`;
