// Symbolic disassembly of pinned densless public artifact. Static calls are named.
// Identical function IDs inherit scaffold names; changed bodies require arithmetic review.
export const prefix = `

`;

export const functions = [
  { name: 'readBoundedInputSlice', originalId: 9, body: `
    OP_DUP OP_INPUTBYTECODE OP_SIZE OP_NIP OP_2OVER OP_ADD OP_GREATERTHANOREQUAL OP_VERIFY OP_INPUTBYTECODE
    OP_OVER OP_SPLIT OP_SWAP OP_SIZE OP_NIP OP_ROT OP_NUMEQUALVERIFY OP_OVER OP_SPLIT OP_DROP OP_DUP OP_SIZE
    OP_NIP OP_ROT OP_NUMEQUALVERIFY
  ` },
  { name: 'millerEvent', originalId: 16, body: `
    NUM BASE_FIELD OP_12 OP_ROLL OP_DUP OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP OP_BIN2NUM OP_SWAP OP_DUP
    OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP OP_BIN2NUM OP_SWAP OP_0 OP_0 OP_PUSHBYTES_1 0x12 OP_PICK OP_1
    OP_GREATERTHANOREQUAL OP_IF OP_2 OP_PICK OP_PUSHBYTES_1 0x20 OP_SPLIT OP_OVER OP_BIN2NUM OP_4 OP_ROLL
    OP_DROP OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_FROMALTSTACK OP_FROMALTSTACK OP_DUP OP_5
    CALL sharedSequence18 OP_SWAP OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_4 OP_PICK OP_PUSHBYTES_1
    0x20 OP_SPLIT OP_OVER OP_BIN2NUM OP_5 CALL sharedSequence18 OP_SWAP OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_DUP OP_7 CALL sharedSequence18 OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_2DROP OP_2DROP OP_ENDIF
    OP_ROT OP_SIZE OP_NIP OP_0 OP_NUMEQUALVERIFY OP_1 OP_PUSHBYTES_1 0x12 OP_PICK OP_1 OP_NUMEQUAL OP_IF OP_8
    OP_PICK OP_NIP OP_ENDIF OP_PUSHBYTES_1 0x12 OP_PICK OP_2 OP_NUMEQUAL OP_IF OP_9 OP_PICK OP_NIP OP_ENDIF
    OP_3 OP_ROLL OP_5 OP_ROLL OP_13 OP_ROLL OP_13 OP_ROLL OP_13 OP_ROLL OP_13 OP_ROLL NUM BASE_FIELD OP_6
    OP_PICK OP_6 OP_PICK CALL sharedSequence3 OP_2 OP_4 OP_PICK OP_5 OP_PICK OP_ADD OP_3 OP_ROLL CALL
    sharedSequence6 OP_2 OP_PICK OP_MOD OP_2 OP_5 OP_PICK OP_6 OP_PICK OP_ADD OP_3 OP_ROLL CALL
    sharedSequence23 OP_PUSHBYTES_1 0x11 OP_ROLL OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP OP_BIN2NUM OP_6 OP_PICK
    OP_MUL OP_11 OP_PICK OP_MOD OP_PUSHBYTES_1 0x12 OP_PICK OP_1 OP_GREATERTHANOREQUAL OP_IF OP_16 OP_PICK
    OP_PUSHBYTES_1 0x12 OP_PICK OP_PUSHBYTES_1 0x14 OP_PICK OP_1 OP_NUMEQUAL OP_IF OP_13 OP_PICK OP_PUSHBYTES_1
    0x13 OP_PICK OP_SUB OP_14 OP_PICK OP_MOD OP_ROT OP_DROP OP_SWAP OP_13 OP_PICK OP_PUSHBYTES_1 0x14 OP_PICK
    OP_SUB OP_14 OP_PICK OP_MOD OP_NIP OP_ENDIF OP_PUSHBYTES_1 0x14 OP_PICK OP_1 OP_NUMEQUAL OP_IF OP_9 OP_PICK
    OP_11 OP_PICK OP_PUSHBYTES_1 0x15 OP_PICK OP_PUSHBYTES_1 0x15 OP_PICK CALL sharedSequence26 OP_ELSE OP_9
    OP_PICK OP_11 OP_PICK OP_2OVER OP_SWAP CALL sharedSequence26 OP_ENDIF OP_3 OP_PICK OP_PUSHBYTES_1 0x20
    OP_SPLIT OP_OVER OP_BIN2NUM OP_5 OP_PICK OP_OVER OP_MUL OP_PUSHBYTES_1 0x11 OP_PICK OP_MOD OP_6 CALL
    sharedSequence18 OP_SWAP OP_TOALTSTACK OP_SWAP OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_OVER OP_SIZE OP_NIP OP_0 OP_NUMEQUALVERIFY OP_2DROP OP_2DROP OP_DROP OP_ENDIF
    OP_PUSHBYTES_1 0x12 OP_ROLL OP_0 OP_NUMEQUAL OP_IF OP_OVER OP_SIZE OP_NIP OP_0 OP_NUMEQUALVERIFY OP_ENDIF
    OP_DUP OP_12 OP_PICK OP_ADD OP_12 OP_ROLL OP_MOD OP_6 OP_ROLL OP_6 OP_ROLL OP_6 OP_ROLL OP_6 OP_ROLL
    OP_TOALTSTACK OP_TOALTSTACK OP_TOALTSTACK OP_TOALTSTACK OP_TOALTSTACK OP_2DROP OP_2DROP OP_2DROP OP_2DROP
    OP_2DROP OP_2DROP OP_DROP OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
  ` },
  { name: 'sharedSequence3', originalId: 18, body: `
    OP_2DUP OP_ADD OP_PUSHBYTES_1 0x40 OP_2OVER CALL sharedSequence6 OP_SWAP CALL sharedSequence4 OP_ROT OP_ROT
    CALL sharedSequence4 OP_DUP OP_ADD
  ` },
  { name: 'sharedSequence4', originalId: 14, body: `
    OP_MUL NUM BASE_FIELD OP_MOD
  ` },
  { name: 'sharedSequence6', originalId: 1, body: `
    OP_SWAP OP_SUB OP_SWAP NUM BASE_FIELD OP_MUL OP_ADD
  ` },
  { name: 'sharedSequence7', originalId: 23, body: `
    OP_2 OP_PICK OP_OVER CALL sharedSequence4 OP_4 OP_PICK OP_3 OP_PICK CALL sharedSequence4 OP_1 OP_OVER OP_3
    OP_PICK CALL sharedSequence6 OP_2 OP_2SWAP OP_ADD OP_6 OP_ROLL OP_6 OP_ROLL OP_ADD OP_2ROT OP_ADD CALL
    sharedSequence4 CALL sharedSequence6
  ` },
  { name: 'sharedSequence10', originalId: 19, body: `
    NUM BASE_FIELD OP_PUSHBYTES_2 0x8000 OP_PUSHBYTES_2 0x8000 OP_PUSHBYTES_1 0x40 OP_PUSHBYTES_1 0x40
    OP_PUSHBYTES_1 0x15 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_PUSHBYTES_1 0x40 OP_4 OP_ROLL OP_DROP OP_SWAP
    OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_FROMALTSTACK OP_FROMALTSTACK OP_PUSHBYTES_1 0x20 OP_ROT
    OP_DROP OP_SWAP OP_ENDIF OP_PUSHBYTES_1 0x16 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_PUSHBYTES_1 0x40 OP_3
    OP_ROLL OP_DROP OP_SWAP OP_TOALTSTACK OP_SWAP OP_FROMALTSTACK OP_PUSHBYTES_1 0x20 OP_NIP OP_ENDIF
    OP_PUSHBYTES_1 0x17 OP_ROLL OP_4 OP_ROLL OP_SPLIT OP_PUSHBYTES_1 0x18 OP_ROLL OP_4 OP_ROLL OP_SPLIT OP_ROT
    OP_5 OP_ROLL OP_SPLIT OP_ROT OP_5 OP_ROLL OP_SPLIT OP_ROT OP_PUSHBYTES_1 0x40 OP_SPLIT OP_SWAP
    OP_PUSHBYTES_1 0x20 OP_SPLIT OP_DUP OP_SIZE OP_NIP OP_PUSHBYTES_1 0x20 OP_NUMEQUALVERIFY OP_REVERSEBYTES
    OP_BIN2NUM OP_8 OP_PICK OP_ADD OP_8 OP_PICK OP_MOD OP_SWAP OP_6 OP_ROLL OP_7 OP_ROLL OP_PUSHBYTES_1 0x19
    OP_ROLL OP_PUSHBYTES_1 0x19 OP_PICK OP_PUSHBYTES_1 0x19 OP_PICK OP_PUSHBYTES_1 0x19 OP_PICK OP_PUSHBYTES_1
    0x19 OP_PICK OP_PUSHBYTES_1 0x19 OP_ROLL OP_PUSHBYTES_1 0x19 OP_ROLL OP_PUSHBYTES_1 0x19 OP_ROLL
    OP_PUSHBYTES_1 0x19 OP_ROLL OP_PUSHBYTES_1 0x19 OP_PICK OP_PUSHBYTES_1 0x19 OP_PICK CALL millerEvent OP_9
    OP_ROLL OP_10 OP_ROLL OP_PUSHBYTES_1 0x18 OP_ROLL OP_PUSHBYTES_1 0x18 OP_ROLL OP_PUSHBYTES_1 0x18 OP_ROLL
    OP_PUSHBYTES_1 0x18 OP_ROLL OP_PUSHBYTES_1 0x18 OP_ROLL OP_7 OP_ROLL OP_8 OP_ROLL OP_9 OP_ROLL OP_10
    OP_ROLL OP_PUSHBYTES_1 0x18 OP_ROLL OP_PUSHBYTES_1 0x18 OP_ROLL CALL millerEvent OP_14 OP_PICK OP_15
    OP_ROLL OP_MUL OP_6 OP_ROLL OP_MUL OP_10 OP_PICK OP_MOD OP_DUP OP_MUL OP_5 OP_ROLL OP_MUL OP_9 OP_PICK
    OP_MOD OP_10 OP_PICK OP_10 OP_PICK OP_ADD OP_13 OP_PICK OP_ROT OP_MUL OP_ADD OP_9 OP_PICK OP_MOD OP_11
    OP_PICK OP_10 OP_PICK OP_ADD OP_13 OP_PICK OP_8 OP_PICK OP_MUL OP_ADD OP_10 OP_PICK OP_MOD OP_13 OP_PICK
    OP_16 OP_ROLL OP_MUL OP_11 OP_ROLL OP_MOD OP_14 OP_PICK OP_16 OP_ROLL OP_4 OP_NUM2BIN OP_REVERSEBYTES
    OP_CAT OP_PUSHBYTES_4 0x00000020 OP_CAT OP_8 OP_ROLL OP_CAT OP_HASH256 OP_2SWAP OP_3 OP_ROLL OP_8 OP_ROLL
    OP_4 OP_ROLL OP_8 OP_ROLL OP_8 OP_ROLL OP_8 OP_ROLL OP_8 OP_ROLL OP_9 OP_ROLL OP_10 OP_ROLL OP_11 OP_ROLL
    OP_DROP OP_11 OP_ROLL OP_DROP OP_11 OP_ROLL OP_DROP OP_11 OP_ROLL OP_DROP
  ` },
  { name: 'sharedSequence11', originalId: 0, body: `
    CALL sharedSequence24 CALL sharedSequence24 CALL sharedSequence24 CALL sharedSequence24 OP_SWAP
    OP_TOALTSTACK OP_SWAP OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
  ` },
  { name: 'sharedSequence12', originalId: 4, body: `
    OP_PICK OP_PUSHBYTES_1 0x16 OP_PICK OP_PUSHBYTES_1 0x18 OP_PICK OP_PUSHBYTES_1 0x1a OP_PICK OP_PUSHBYTES_1
    0x1c OP_PICK OP_PUSHBYTES_1 0x1e CALL sharedSequence28
  ` },
  { name: 'sharedSequence13', originalId: 2, body: `
    CALL sharedSequence24 OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK
  ` },
  { name: 'sharedSequence14', originalId: 24, body: `
    OP_PUSHBYTES_1 0x15 OP_PICK OP_PUSHBYTES_1 0x15 OP_PICK OP_10 OP_PICK OP_12 OP_PICK OP_14 OP_PICK OP_16
    OP_PICK NUM BASE_FIELD OP_7 OP_ROLL OP_8 OP_ROLL OP_ADD OP_OVER OP_MOD OP_DUP OP_NUMEQUALVERIFY OP_8
    OP_PICK OP_8 OP_PICK CALL sharedSequence3 OP_PUSHBYTES_1 0x40 OP_8 OP_ROLL OP_PUSHBYTES_1 0x40 OP_6 OP_PICK
    OP_5 OP_ROLL CALL sharedSequence6 CALL sharedSequence6 OP_2 OP_PICK OP_MOD OP_PUSHBYTES_1 0x40 OP_8 OP_ROLL
    OP_PUSHBYTES_1 0x40 OP_7 OP_PICK OP_5 OP_ROLL CALL sharedSequence6 CALL sharedSequence23 OP_8 OP_ROLL
    OP_DROP
  ` },
  { name: 'sharedSequence15', originalId: 5, body: `
    OP_PICK OP_11 OP_PICK OP_13 OP_PICK OP_15 OP_PICK OP_PUSHBYTES_1 0x11 OP_PICK
  ` },
  { name: 'sharedSequence16', originalId: 6, body: `
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
  ` },
  { name: 'sharedSequence17', originalId: 10, body: `
    OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP OP_BIN2NUM OP_SWAP OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP OP_BIN2NUM
    OP_SWAP
  ` },
  { name: 'sharedSequence18', originalId: 3, body: `
    OP_ROLL OP_DROP OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK
  ` },
  { name: 'sharedSequence19', originalId: 7, body: `
    OP_ADD OP_3 OP_PICK OP_5 OP_PICK OP_3 OP_ROLL OP_4 OP_ROLL
  ` },
  { name: 'sharedSequence20', originalId: 11, body: `
    OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP OP_SIZE OP_NIP OP_PUSHBYTES_1 0x20 OP_NUMEQUALVERIFY
  ` },
  { name: 'sharedSequence21', originalId: 12, body: `
    OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP
  ` },
  { name: 'sharedSequence22', originalId: 17, body: `
    OP_SWAP OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_8 OP_ROLL OP_DROP
  ` },
  { name: 'sharedSequence23', originalId: 20, body: `
    CALL sharedSequence6 OP_2 OP_PICK OP_MOD OP_1 OP_OVER OP_6 OP_ROLL CALL sharedSequence6 OP_1 OP_3 OP_PICK
    OP_6 OP_ROLL CALL sharedSequence6 OP_8 OP_ROLL OP_8 OP_ROLL CALL sharedSequence7 OP_1 OP_6 OP_ROLL OP_3
    OP_ROLL CALL sharedSequence6 OP_4 OP_PICK OP_MOD OP_1 OP_6 OP_ROLL OP_3 OP_ROLL CALL sharedSequence6 OP_4
    OP_ROLL OP_MOD
  ` },
  { name: 'sharedSequence24', originalId: 8, body: `
    OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK
  ` },
  { name: 'sharedSequence25', originalId: 13, body: `
    OP_ROLL OP_DROP CALL sharedSequence13 CALL sharedSequence13
  ` },
  { name: 'sharedSequence26', originalId: 21, body: `
    CALL sharedSequence14 CALL sharedSequence13 CALL sharedSequence22 CALL sharedSequence13 CALL
    sharedSequence22 CALL sharedSequence13 CALL sharedSequence22 CALL sharedSequence13 OP_SWAP OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
  ` },
  { name: 'sharedSequence27', originalId: 15, body: `
    OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK CALL sharedSequence11 OP_FROMALTSTACK OP_FROMALTSTACK
  ` },
  { name: 'sharedSequence28', originalId: 22, body: `
    OP_PICK CALL sharedSequence10 OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10
    OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL OP_10 OP_ROLL
  ` },
];

export const main = `
    NUM BASE_FIELD OP_INPUTINDEX OP_DUP OP_3 OP_LESSTHAN OP_VERIFY OP_PUSHBYTES_5 0x2110012141 OP_OVER OP_1
    OP_NUMEQUAL OP_IF OP_PUSHBYTES_6 0x004208018400 OP_NIP OP_ENDIF OP_OVER OP_2 OP_NUMEQUAL OP_IF
    OP_PUSHBYTES_6 0x400402418800 OP_NIP OP_ENDIF OP_4 OP_2 OP_PICK OP_1 OP_NUMEQUAL OP_IF OP_DROP OP_14
    OP_ENDIF OP_2 OP_PICK OP_2 OP_NUMEQUAL OP_IF OP_PUSHBYTES_1 0x18 OP_NIP OP_ENDIF OP_10 OP_3 OP_PICK OP_1
    OP_NUMEQUAL OP_IF OP_DROP OP_10 OP_ENDIF OP_3 OP_PICK OP_2 OP_NUMEQUAL OP_IF OP_DROP OP_11 OP_ENDIF OP_0
    OP_4 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_PUSHBYTES_2 0xa003 OP_PUSHBYTES_2 0x970e OP_0 CALL
    readBoundedInputSlice OP_NIP OP_ENDIF OP_4 OP_PICK OP_1 OP_NUMEQUAL OP_IF OP_PUSHBYTES_2 0x4003
    OP_PUSHBYTES_2 0xb80e OP_1 CALL readBoundedInputSlice OP_NIP OP_ENDIF OP_4 OP_PICK OP_2 OP_NUMEQUAL OP_IF
    OP_PUSHBYTES_2 0xa003 OP_PUSHBYTES_2 0x5e0e OP_2 CALL readBoundedInputSlice OP_NIP OP_ENDIF OP_PUSHBYTES_2
    0xc001 OP_3 OP_3 CALL readBoundedInputSlice OP_0 OP_6 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_PUSHBYTES_2 0x2801
    OP_3 OP_1 CALL readBoundedInputSlice OP_NIP OP_ENDIF OP_6 OP_PICK OP_1 OP_NUMEQUAL OP_IF OP_PUSHBYTES_2
    0x2801 OP_3 OP_2 CALL readBoundedInputSlice OP_NIP OP_ENDIF OP_6 OP_PICK OP_2 OP_NUMEQUAL OP_IF
    OP_PUSHBYTES_2 0x2801 OP_3 OP_4 CALL readBoundedInputSlice OP_NIP OP_ENDIF OP_2 OP_PICK OP_SIZE OP_NIP OP_0
    OP_GREATERTHAN OP_VERIFY OP_SWAP OP_PUSHBYTES_1 0x20 OP_SPLIT OP_SWAP OP_BIN2NUM OP_SWAP CALL
    sharedSequence20 CALL sharedSequence20 CALL sharedSequence20 CALL sharedSequence20 CALL sharedSequence20
    CALL sharedSequence20 CALL sharedSequence20 CALL sharedSequence17 CALL sharedSequence17 CALL
    sharedSequence17 OP_SIZE OP_NIP OP_0 OP_NUMEQUALVERIFY OP_14 OP_ROLL OP_PUSHBYTES_1 0x28 OP_SPLIT OP_SWAP
    OP_BIN2NUM OP_SWAP CALL sharedSequence17 CALL sharedSequence17 CALL sharedSequence17 CALL sharedSequence17
    OP_SIZE OP_NIP OP_0 OP_NUMEQUALVERIFY OP_8 OP_ROLL OP_PUSHBYTES_1 0x21 OP_NUM2BIN OP_PUSHBYTES_1 0x20
    OP_SPLIT OP_DROP OP_PUSHBYTES_1 0x17 OP_ROLL OP_PUSHBYTES_1 0x12 OP_ROLL OP_6 OP_ROLL OP_6 OP_ROLL OP_6
    OP_ROLL OP_6 OP_ROLL OP_0 OP_PUSHBYTES_1 0x17 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_DROP OP_1 OP_ENDIF
    OP_PUSHBYTES_1 0x17 OP_ROLL OP_0 OP_NUMEQUAL OP_IF OP_PUSHBYTES_1 0x16 OP_PICK OP_4 OP_MOD OP_DUP OP_2
    OP_LESSTHANOREQUAL OP_VERIFY OP_PUSHBYTES_2 0x8000 OP_PUSHBYTES_1 0x40 OP_2 OP_PICK OP_0 OP_NUMEQUAL OP_IF
    OP_PUSHBYTES_1 0x40 OP_ROT OP_DROP OP_SWAP OP_PUSHBYTES_1 0x20 OP_NIP OP_ENDIF OP_9 OP_PICK OP_2 OP_PICK
    OP_SPLIT OP_10 OP_PICK OP_3 OP_PICK OP_SPLIT OP_2 OP_PICK OP_PUSHBYTES_1 0x40 OP_SPLIT OP_OVER
    OP_PUSHBYTES_1 0x20 OP_SPLIT OP_DUP OP_SIZE OP_NIP OP_PUSHBYTES_1 0x20 OP_NUMEQUALVERIFY OP_DUP
    OP_REVERSEBYTES OP_DUP OP_BIN2NUM OP_PUSHBYTES_1 0x24 OP_PICK OP_ADD OP_PUSHBYTES_1 0x24 OP_PICK OP_MOD
    OP_3 OP_PICK OP_5 OP_PICK OP_PUSHBYTES_1 0x15 OP_ROLL OP_DROP CALL sharedSequence27 OP_7 OP_PICK
    OP_PUSHBYTES_1 0x14 OP_ROLL OP_DROP OP_SWAP OP_TOALTSTACK CALL sharedSequence11 OP_FROMALTSTACK OP_8
    OP_PICK OP_11 OP_PICK OP_15 OP_PICK OP_PUSHBYTES_1 0x1f OP_PICK OP_PUSHBYTES_1 0x21 OP_PICK OP_PUSHBYTES_1
    0x23 OP_PICK OP_PUSHBYTES_1 0x25 OP_PICK OP_PUSHBYTES_1 0x16 OP_PICK OP_PUSHBYTES_1 0x18 OP_PICK
    OP_PUSHBYTES_1 0x1a OP_PICK OP_PUSHBYTES_1 0x1c OP_PICK OP_PUSHBYTES_1 0x25 OP_PICK OP_PUSHBYTES_1 0x27
    OP_PICK CALL millerEvent OP_PUSHBYTES_1 0x1b OP_PICK OP_PUSHBYTES_1 0x1c OP_PICK OP_MUL OP_5 OP_PICK OP_MUL
    OP_PUSHBYTES_1 0x2b OP_PICK OP_MOD OP_PUSHBYTES_1 0x1f OP_PICK OP_PUSHBYTES_1 0x2c OP_PICK OP_ADD
    OP_PUSHBYTES_1 0x1e OP_PICK OP_2 OP_PICK OP_MUL OP_ADD OP_PUSHBYTES_1 0x2c OP_PICK OP_MOD OP_PUSHBYTES_1
    0x20 CALL sharedSequence25 OP_SWAP OP_TOALTSTACK CALL sharedSequence11 CALL sharedSequence16
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_PUSHBYTES_1 0x1e OP_PICK OP_PUSHBYTES_1 0x2c OP_PICK
    OP_ADD OP_PUSHBYTES_1 0x1e OP_PICK OP_9 OP_PICK OP_MUL OP_ADD OP_PUSHBYTES_1 0x2c OP_PICK OP_MOD
    OP_PUSHBYTES_1 0x1f CALL sharedSequence25 CALL sharedSequence11 CALL sharedSequence16 OP_FROMALTSTACK
    OP_FROMALTSTACK OP_PUSHBYTES_1 0x1d OP_PICK OP_PUSHBYTES_1 0x27 OP_PICK OP_MUL OP_PUSHBYTES_1 0x2c OP_PICK
    OP_MOD OP_PUSHBYTES_1 0x1e OP_ROLL OP_DROP CALL sharedSequence13 CALL sharedSequence24 OP_SWAP
    OP_TOALTSTACK CALL sharedSequence11 CALL sharedSequence16 OP_FROMALTSTACK OP_7 OP_PICK OP_PUSHBYTES_1 0x1d
    OP_ROLL OP_DROP CALL sharedSequence13 CALL sharedSequence24 CALL sharedSequence11 CALL sharedSequence16
    OP_PUSHBYTES_1 0x1b OP_PICK OP_3 OP_4 OP_NUM2BIN OP_REVERSEBYTES OP_CAT OP_PUSHBYTES_4 0x00000020 OP_CAT
    OP_7 OP_PICK OP_CAT OP_HASH256 OP_PUSHBYTES_1 0x1c OP_ROLL OP_DROP CALL sharedSequence13 OP_SWAP
    OP_TOALTSTACK CALL sharedSequence27 OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_4 OP_PICK OP_PUSHBYTES_1 0x19 OP_ROLL OP_DROP CALL
    sharedSequence13 CALL sharedSequence11 OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_3 OP_PICK OP_PUSHBYTES_1 0x18 CALL sharedSequence18 CALL
    sharedSequence27 OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_2 OP_PICK OP_PUSHBYTES_1 0x17 CALL
    sharedSequence18 OP_SWAP OP_TOALTSTACK CALL sharedSequence11 OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_OVER OP_PUSHBYTES_1 0x16 CALL sharedSequence18 CALL sharedSequence11
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK CALL sharedSequence21 OP_2DROP OP_ENDIF OP_PUSHBYTES_1 0x16
    OP_PICK OP_2 OP_2 OP_PICK OP_0 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x17 OP_PICK OP_2 OP_3
    OP_PICK OP_0 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x17 OP_PICK OP_0 OP_ADD OP_8
    OP_PICK OP_10 OP_PICK OP_3 OP_ROLL OP_4 OP_ROLL OP_PUSHBYTES_1 0x13 OP_PICK OP_PUSHBYTES_1 0x15 OP_PICK
    OP_PUSHBYTES_1 0x17 OP_PICK OP_PUSHBYTES_1 0x19 OP_PICK OP_10 OP_PICK OP_12 OP_PICK OP_14 OP_PICK OP_16
    OP_PICK OP_PUSHBYTES_1 0x19 OP_PICK OP_PUSHBYTES_1 0x1b OP_PICK OP_PUSHBYTES_1 0x21 OP_PICK OP_PUSHBYTES_1
    0x17 OP_PICK OP_PUSHBYTES_1 0x19 OP_PICK OP_PUSHBYTES_1 0x1b OP_PICK OP_PUSHBYTES_1 0x1d OP_PICK
    OP_PUSHBYTES_1 0x1f CALL sharedSequence28 OP_PUSHBYTES_1 0x21 OP_PICK OP_2 OP_13 OP_PICK OP_2 OP_ADD OP_MUL
    OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x22 OP_PICK OP_2 OP_14 OP_PICK OP_2 OP_ADD OP_1ADD OP_MUL
    OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x22 OP_PICK OP_1ADD OP_3 OP_PICK OP_5 OP_PICK OP_3 OP_ROLL OP_4
    OP_ROLL OP_PUSHBYTES_1 0x1e OP_PICK OP_PUSHBYTES_1 0x20 OP_PICK OP_PUSHBYTES_1 0x22 OP_PICK OP_PUSHBYTES_1
    0x24 CALL sharedSequence15 OP_PUSHBYTES_1 0x24 OP_PICK OP_PUSHBYTES_1 0x26 OP_PICK OP_PUSHBYTES_1 0x2c CALL
    sharedSequence12 OP_PUSHBYTES_1 0x2c OP_PICK OP_2 OP_PUSHBYTES_1 0x18 OP_PICK OP_4 OP_ADD OP_MUL
    OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x2d OP_PICK OP_2 OP_PUSHBYTES_1 0x19 OP_PICK OP_4 OP_ADD OP_1ADD
    OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x2d OP_PICK OP_2 CALL sharedSequence19 OP_PUSHBYTES_1 0x29
    OP_PICK OP_PUSHBYTES_1 0x2b OP_PICK OP_PUSHBYTES_1 0x2d OP_PICK OP_PUSHBYTES_1 0x2f CALL sharedSequence15
    OP_PUSHBYTES_1 0x2f OP_PICK OP_PUSHBYTES_1 0x31 OP_PICK OP_PUSHBYTES_1 0x37 CALL sharedSequence12
    OP_PUSHBYTES_1 0x37 OP_PICK OP_2 OP_PUSHBYTES_1 0x23 OP_PICK OP_6 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD
    OP_PUSHBYTES_1 0x38 OP_PICK OP_2 OP_PUSHBYTES_1 0x24 OP_PICK OP_6 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4
    OP_MOD OP_PUSHBYTES_1 0x38 OP_PICK OP_3 CALL sharedSequence19 OP_PUSHBYTES_1 0x34 OP_PICK OP_PUSHBYTES_1
    0x36 OP_PICK OP_PUSHBYTES_1 0x38 OP_PICK OP_PUSHBYTES_1 0x3a CALL sharedSequence15 OP_PUSHBYTES_1 0x3a
    OP_PICK OP_PUSHBYTES_1 0x3c OP_PICK OP_PUSHBYTES_1 0x42 CALL sharedSequence12 OP_PUSHBYTES_1 0x42 OP_PICK
    OP_2 OP_PUSHBYTES_1 0x2e OP_PICK OP_8 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x43 OP_PICK
    OP_2 OP_PUSHBYTES_1 0x2f OP_PICK OP_8 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x43
    OP_PICK OP_4 CALL sharedSequence19 OP_PUSHBYTES_1 0x3f OP_PICK OP_PUSHBYTES_1 0x41 OP_PICK OP_PUSHBYTES_1
    0x43 OP_PICK OP_PUSHBYTES_1 0x45 CALL sharedSequence15 OP_PUSHBYTES_1 0x45 OP_PICK OP_PUSHBYTES_1 0x47
    OP_PICK OP_PUSHBYTES_1 0x4d CALL sharedSequence12 OP_PUSHBYTES_1 0x4d OP_PICK OP_2 OP_PUSHBYTES_1 0x39
    OP_PICK OP_10 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x4e OP_PICK OP_2 OP_PUSHBYTES_1 0x3a
    OP_PICK OP_10 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x4e OP_PICK OP_5 CALL
    sharedSequence19 OP_PUSHBYTES_1 0x4a OP_PICK OP_PUSHBYTES_1 0x4c OP_PICK OP_PUSHBYTES_1 0x4e OP_PICK
    OP_PUSHBYTES_1 0x50 CALL sharedSequence15 OP_PUSHBYTES_1 0x50 OP_PICK OP_PUSHBYTES_1 0x52 OP_PICK
    OP_PUSHBYTES_1 0x58 CALL sharedSequence12 OP_PUSHBYTES_1 0x58 OP_PICK OP_2 OP_PUSHBYTES_1 0x44 OP_PICK
    OP_12 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x59 OP_PICK OP_2 OP_PUSHBYTES_1 0x45 OP_PICK
    OP_12 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x59 OP_PICK OP_6 CALL sharedSequence19
    OP_PUSHBYTES_1 0x55 OP_PICK OP_PUSHBYTES_1 0x57 OP_PICK OP_PUSHBYTES_1 0x59 OP_PICK OP_PUSHBYTES_1 0x5b
    CALL sharedSequence15 OP_PUSHBYTES_1 0x5b OP_PICK OP_PUSHBYTES_1 0x5d OP_PICK OP_PUSHBYTES_1 0x63 CALL
    sharedSequence12 OP_PUSHBYTES_1 0x63 OP_PICK OP_2 OP_PUSHBYTES_1 0x4f OP_PICK OP_14 OP_ADD OP_MUL
    OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x64 OP_PICK OP_2 OP_PUSHBYTES_1 0x50 OP_PICK OP_14 OP_ADD OP_1ADD
    OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1 0x64 OP_PICK OP_7 CALL sharedSequence19 OP_PUSHBYTES_1 0x60
    OP_PICK OP_PUSHBYTES_1 0x62 OP_PICK OP_PUSHBYTES_1 0x64 OP_PICK OP_PUSHBYTES_1 0x66 CALL sharedSequence15
    OP_PUSHBYTES_1 0x66 OP_PICK OP_PUSHBYTES_1 0x68 OP_PICK OP_PUSHBYTES_1 0x6e CALL sharedSequence12
    OP_PUSHBYTES_1 0x6e OP_PICK OP_2 OP_PUSHBYTES_1 0x5a OP_PICK OP_16 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD
    OP_PUSHBYTES_1 0x6f OP_PICK OP_2 OP_PUSHBYTES_1 0x5b OP_PICK OP_16 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4
    OP_MOD OP_PUSHBYTES_1 0x6f OP_PICK OP_8 CALL sharedSequence19 OP_PUSHBYTES_1 0x6b OP_PICK OP_PUSHBYTES_1
    0x6d OP_PICK OP_PUSHBYTES_1 0x6f OP_PICK OP_PUSHBYTES_1 0x71 CALL sharedSequence15 OP_PUSHBYTES_1 0x71
    OP_PICK OP_PUSHBYTES_1 0x73 OP_PICK OP_PUSHBYTES_1 0x79 CALL sharedSequence12 OP_PUSHBYTES_1 0x79 OP_PICK
    OP_2 OP_PUSHBYTES_1 0x65 OP_PICK OP_PUSHBYTES_1 0x12 OP_ADD OP_MUL OP_RSHIFTNUM OP_4 OP_MOD OP_PUSHBYTES_1
    0x7a OP_ROLL OP_2 OP_PUSHBYTES_1 0x66 OP_ROLL OP_PUSHBYTES_1 0x12 OP_ADD OP_1ADD OP_MUL OP_RSHIFTNUM OP_4
    OP_MOD OP_PUSHBYTES_1 0x79 OP_PICK OP_9 CALL sharedSequence19 OP_PUSHBYTES_1 0x75 OP_PICK OP_PUSHBYTES_1
    0x77 OP_PICK OP_PUSHBYTES_1 0x79 OP_PICK OP_PUSHBYTES_1 0x7b CALL sharedSequence15 OP_PUSHBYTES_1 0x7b
    OP_PICK OP_PUSHBYTES_1 0x7d OP_PICK OP_PUSHBYTES_2 0x8300 CALL sharedSequence12 OP_PUSHBYTES_2 0x8100
    OP_ROLL OP_10 OP_GREATERTHAN OP_IF OP_0 OP_0 OP_PUSHBYTES_2 0x8300 OP_PICK OP_10 OP_ADD OP_3 OP_PICK OP_5
    OP_PICK OP_3 OP_PICK OP_5 OP_PICK OP_PUSHBYTES_2 0x8200 OP_PICK OP_PUSHBYTES_2 0x8400 OP_PICK
    OP_PUSHBYTES_2 0x8600 OP_PICK OP_PUSHBYTES_2 0x8800 OP_PICK OP_13 OP_PICK OP_15 OP_PICK OP_PUSHBYTES_1 0x11
    OP_PICK OP_PUSHBYTES_1 0x13 OP_PICK OP_PUSHBYTES_2 0x8800 OP_PICK OP_PUSHBYTES_2 0x8a00 OP_PICK
    OP_PUSHBYTES_2 0x9000 OP_PICK OP_PUSHBYTES_1 0x18 OP_PICK OP_PUSHBYTES_1 0x1a OP_PICK OP_PUSHBYTES_1 0x1c
    OP_PICK OP_PUSHBYTES_1 0x1e OP_PICK OP_PUSHBYTES_1 0x20 OP_PICK CALL sharedSequence10 OP_10 OP_PICK
    OP_PUSHBYTES_1 0x18 CALL sharedSequence18 CALL sharedSequence27 OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_9 OP_PICK OP_PUSHBYTES_1 0x17 CALL sharedSequence18 OP_SWAP OP_TOALTSTACK CALL
    sharedSequence11 OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_8 OP_PICK
    OP_PUSHBYTES_1 0x16 CALL sharedSequence18 CALL sharedSequence11 OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_7 OP_PICK OP_PUSHBYTES_1 0x15 OP_ROLL OP_DROP CALL sharedSequence27 OP_6 OP_PICK
    OP_PUSHBYTES_1 0x14 OP_ROLL OP_DROP OP_SWAP OP_TOALTSTACK CALL sharedSequence11 OP_FROMALTSTACK OP_5
    OP_PICK OP_PUSHBYTES_1 0x13 OP_ROLL OP_DROP CALL sharedSequence11 OP_4 OP_PICK OP_PUSHBYTES_1 0x12 CALL
    sharedSequence25 CALL sharedSequence24 OP_SWAP CALL sharedSequence16 OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_3 OP_PICK OP_PUSHBYTES_1 0x11 CALL
    sharedSequence25 OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP CALL
    sharedSequence16 OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_2
    OP_PICK OP_16 CALL sharedSequence25 OP_SWAP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK OP_SWAP CALL
    sharedSequence16 OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_FROMALTSTACK OP_OVER OP_15 CALL
    sharedSequence25 OP_SWAP OP_TOALTSTACK OP_SWAP CALL sharedSequence16 OP_FROMALTSTACK OP_FROMALTSTACK
    OP_FROMALTSTACK OP_DUP OP_14 CALL sharedSequence25 OP_SWAP CALL sharedSequence16 OP_FROMALTSTACK
    OP_FROMALTSTACK OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_DROP OP_ENDIF OP_SWAP OP_SIZE
    OP_NIP OP_0 OP_NUMEQUAL OP_SWAP OP_SIZE OP_NIP OP_0 OP_NUMEQUAL OP_BOOLAND OP_VERIFY OP_4 OP_ROLL
    OP_PUSHBYTES_1 0x00 OP_CAT OP_BIN2NUM OP_PUSHBYTES_1 0x28 OP_NUM2BIN OP_8 OP_ROLL OP_PUSHBYTES_2 0x8000
    OP_PICK OP_MOD OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_CAT OP_7 OP_ROLL OP_PUSHBYTES_1 0x7f OP_PICK OP_MOD
    OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_7 OP_ROLL OP_PUSHBYTES_1 0x7f OP_PICK OP_MOD OP_PUSHBYTES_1 0x20
    OP_NUM2BIN OP_CAT OP_CAT OP_5 OP_ROLL OP_PUSHBYTES_1 0x7d OP_PICK OP_MOD OP_PUSHBYTES_1 0x20 OP_NUM2BIN
    OP_5 OP_ROLL OP_PUSHBYTES_1 0x7d OP_PICK OP_MOD OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_CAT OP_4 OP_ROLL
    OP_PUSHBYTES_1 0x7c OP_PICK OP_MOD OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_4 OP_ROLL OP_PUSHBYTES_1 0x7c OP_PICK
    OP_MOD OP_PUSHBYTES_1 0x20 OP_NUM2BIN OP_4 OP_ROLL OP_PUSHBYTES_1 0x7c OP_ROLL OP_MOD OP_PUSHBYTES_1 0x20
    OP_NUM2BIN OP_CAT OP_CAT OP_CAT OP_CAT OP_PUSHBYTES_1 0x76 OP_ROLL OP_EQUALVERIFY CALL sharedSequence21
    CALL sharedSequence21 CALL sharedSequence21 CALL sharedSequence21 CALL sharedSequence21 CALL
    sharedSequence21 OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_2DROP OP_1
`;
