// Universal certificate for the grouped GLV accumulator invariant used by the
// projective GLV-to-Miller handoff.
//
// The generated MSM starts at (0,1,0), conditionally doubles a finite Jacobian
// accumulator, then adds zero to two points from fixed affine tables. This
// certificate binds the argument below to those exact generated kernels and all
// 30 serialized table entries. It proves by an exhaustive geometric case split
// that every reachable accumulator has Y != 0, including the projective
// infinity states produced by inverse addition. The deterministic end-to-end
// cases at the end are additional checks, not the basis of the universal claim.
import {
  bn254, Fp, Fp12, millerBatchOps, pairsFor, singlePairMiller, vk,
} from './_millermath.mjs';
import { millerFusedAffineOps } from './_residuemath.mjs';
import {
  GLV_LAMBDA, GLV_R, GLV_SPLIT_TABLE_HEX, VKXGLV_SPLIT_GROUPS,
  VKXGLV_SPLIT_ITERS, genCash, glvDecomposeJoint, vkxGlvSplitStateAt,
} from './gen_vkx_glv.mjs';

const P = 21888242871839275222246405745257275088696311157297823662689037894645226208583n;
const R = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
const BN_X = 4965661367192848881n;
const TABLE_ENTRIES = 15;
const TABLE_ENTRY_BYTES = 64;
const assert = (condition, message) => { if (!condition) throw new Error(message); };

// Exact Pocklington certificates for both 254-bit primes. Values below 10^9
// are proved by complete trial division; every larger node lists prime factors
// of n-1 whose product exceeds sqrt(n). Base 2 satisfies the Pocklington
// congruences for every listed factor.
const pocklingtonFactors = new Map([
  [P, [13427688667394608761327070753331941386769n]],
  [13427688667394608761327070753331941386769n, [2480874801745591n, 173171039n]],
  [2480874801745591n, [35385462869n]],
  [35385462869n, [1263766531n]],
  [1263766531n, [3557n, 911n]],
  [R, [13818364434197438864469338081n, 1670836401704629n]],
  [13818364434197438864469338081n, [65865678001877903n]],
  [65865678001877903n, [639533339n]],
  [1670836401704629n, [5156902474397n]],
  [5156902474397n, [12048837557n]],
  [12048837557n, [93001n, 661n]],
]);
const gcd = (left, right) => {
  while (right !== 0n) [left, right] = [right, left % right];
  return left < 0n ? -left : left;
};
const modPow = (base, exponent, modulus) => {
  let result = 1n;
  base %= modulus;
  while (exponent !== 0n) {
    if (exponent & 1n) result = result * base % modulus;
    base = base * base % modulus;
    exponent >>= 1n;
  }
  return result;
};
const provenPrimes = new Set();
const provePrime = (candidate) => {
  if (provenPrimes.has(candidate)) return;
  assert(candidate >= 2n, `${candidate} is not prime`);
  if (candidate < 1_000_000_000n) {
    if (candidate !== 2n) {
      assert(candidate % 2n !== 0n, `${candidate} has factor 2`);
      for (let divisor = 3n; divisor * divisor <= candidate; divisor += 2n) {
        assert(candidate % divisor !== 0n, `${candidate} has factor ${divisor}`);
      }
    }
  } else {
    const factors = pocklingtonFactors.get(candidate);
    assert(factors !== undefined, `missing Pocklington factors for ${candidate}`);
    let knownFactor = 1n;
    factors.forEach((factor) => {
      provePrime(factor);
      assert((candidate - 1n) % factor === 0n, `${factor} does not divide ${candidate}-1`);
      knownFactor *= factor;
    });
    assert(knownFactor * knownFactor > candidate,
      `known factor of ${candidate}-1 does not exceed sqrt(${candidate})`);
    assert(modPow(2n, candidate - 1n, candidate) === 1n,
      `base-2 Fermat congruence failed for ${candidate}`);
    factors.forEach((factor) => {
      const pocklingtonTerm = (modPow(2n, (candidate - 1n) / factor, candidate) + candidate - 1n) % candidate;
      assert(gcd(pocklingtonTerm, candidate) === 1n,
        `base-2 Pocklington gcd failed for ${candidate}, factor ${factor}`);
    });
  }
  provenPrimes.add(candidate);
};
provePrime(P);
provePrime(R);

const curve = bn254.G1.Point.CURVE();
assert(curve.p === P && Fp.ORDER === P, 'BN254 G1 field modulus changed');
assert(curve.n === R && bn254.fields.Fr.ORDER === R && GLV_R === R,
  'BN254 G1 subgroup order changed');
assert(curve.a === 0n && curve.b === 3n, 'BN254 G1 curve equation changed');
assert(curve.h === 1n, 'BN254 G1 cofactor is not one');
assert((P & 1n) === 1n && (R & 1n) === 1n && gcd(2n, R) === 1n,
  'field and subgroup orders must be odd');
const expectedP = 36n * BN_X ** 4n + 36n * BN_X ** 3n + 24n * BN_X ** 2n + 6n * BN_X + 1n;
const expectedR = 36n * BN_X ** 4n + 36n * BN_X ** 3n + 18n * BN_X ** 2n + 6n * BN_X + 1n;
const trace = 6n * BN_X ** 2n + 1n;
assert(expectedP === P && expectedR === R && P + 1n - trace === R,
  'BN family parameters do not give a cofactor-one G1 order');

// Pin the theorem to the two exact grouped/projective contracts generated by
// the one-transaction builder: windows [0,29) and [29,64), with the final input
// carrying the shared table at byte 233.
const sharedTable = { inputIndex: 1, dataOffset: 233 };
const generatedSources = [
  genCash(0, 29, true, false, true, sharedTable, false, true, true),
  genCash(29, 64, false, true, true, sharedTable, false, true, true),
];
const expectedKernel = `function jacDouble(int x, int y, int z) returns (int, int, int) {
    int a = (x * x) % ${P}; int b = (y * y) % ${P}; int c = (b * b) % ${P};
    int d = (4 * x * b) % ${P};
    int e = (a * 3) % ${P}; int f = (e * e) % ${P};
    int nx = (f - 2 * d + ${2n * P}) % ${P};
    int ny = ((d - nx + ${P}) * e + ${8n * P} - c * 8) % ${P};
    int nz = (2 * y * z) % ${P};
    return nx, ny, nz;
}
function jacAddAffine(int aX, int aY, int aZ, int bX, int bY) returns (int, int, int) {
    int rx = bX; int ry = bY; int rz = 1;
    if (aZ != 0) {
        int z1z1 = (aZ * aZ) % ${P};
        int u2 = (bX * z1z1) % ${P};
        int s2 = (z1z1 * aZ * bY) % ${P};
        int h = (u2 + ${P} - aX) % ${P}; int hh = (h * h) % ${P}; int hhh = (h * hh) % ${P};
        int rr = (s2 + ${P} - aY) % ${P}; int vv = (hh * aX) % ${P};
        int anx = (rr * rr + ${3n * P} - hhh - 2 * vv) % ${P};
        int ayhhh = (aY * hhh) % ${P};
        int any = ((vv - anx + ${P}) * rr + ${P} - ayhhh) % ${P};
        int anz = (aZ * h) % ${P};
        rx = anx; ry = any; rz = anz;
    }
    return rx, ry, rz;
}`;
const transitionLines = [
  '            if (rZ != 0) { (int dx, int dy, int dz) = jacDouble(rX, rY, rZ); rX = dx; rY = dy; rZ = dz; }',
  '            if (aX != 0) { (int ax, int ay, int az) = jacAddAffine(rX, rY, rZ, aX, aY); if (ay == 0) { (ax, ay, az) = jacDouble(rX, rY, rZ); } rX = ax; rY = ay; rZ = az; }',
  '            if (aX64 != 0) { (int ax64, int ay64, int az64) = jacAddAffine(rX, rY, rZ, aX64, aY64); if (ay64 == 0) { (ax64, ay64, az64) = jacDouble(rX, rY, rZ); } rX = ax64; rY = ay64; rZ = az64; }',
];
generatedSources.forEach((source, sourceIndex) => {
  const kernelStart = source.indexOf('function jacDouble');
  const kernelEnd = source.indexOf('\ncontract VkxGlvChunk()');
  assert(kernelStart >= 0 && kernelEnd > kernelStart, `missing grouped kernel in input ${sourceIndex}`);
  assert(source.slice(kernelStart, kernelEnd) === expectedKernel,
    `grouped Jacobian kernel changed in input ${sourceIndex}`);
  transitionLines.forEach((line) => {
    assert(source.split(line).length === 2, `grouped transition changed in input ${sourceIndex}`);
  });
});
assert(generatedSources[0].includes('        int rX = 0; int rY = 1; int rZ = 0;'),
  'grouped GLV identity initialization changed');

// Bind all fixed additions to the exact table bytes used by those contracts.
// Every entry is canonical, finite, nonzero-Y, and the expected prime-subgroup
// sum of the four GLV lanes at its exact 64-bit group shift.
const fromLe = (bytes) => {
  let value = 0n;
  for (let index = bytes.length - 1; index >= 0; index -= 1) {
    value = value << 8n | BigInt(bytes[index]);
  }
  return value;
};
const tableBytes = Buffer.from(GLV_SPLIT_TABLE_HEX.slice(2), 'hex');
assert(VKXGLV_SPLIT_GROUPS === 2 && VKXGLV_SPLIT_ITERS === 64,
  'grouped GLV dimensions changed');
assert(tableBytes.length === VKXGLV_SPLIT_GROUPS * TABLE_ENTRIES * TABLE_ENTRY_BYTES,
  'grouped GLV table length changed');
assert(GLV_LAMBDA !== 1n && GLV_LAMBDA ** 3n % R === 1n, 'invalid GLV eigenvalue');
const lanePoints = [
  vk.ic[1],
  vk.ic[1].multiplyUnsafe(GLV_LAMBDA),
  vk.ic[2],
  vk.ic[2].multiplyUnsafe(GLV_LAMBDA),
];
let checkedTableEntries = 0;
for (let group = 0; group < VKXGLV_SPLIT_GROUPS; group += 1) {
  const shift = 1n << BigInt(group * VKXGLV_SPLIT_ITERS);
  for (let mask = 1; mask <= TABLE_ENTRIES; mask += 1) {
    const offset = (group * TABLE_ENTRIES + mask - 1) * TABLE_ENTRY_BYTES;
    const x = fromLe(tableBytes.subarray(offset, offset + 32));
    const y = fromLe(tableBytes.subarray(offset + 32, offset + 64));
    assert(x > 0n && x < P && y > 0n && y < P,
      `table point ${group}:${mask} is not canonical finite/nonzero-coordinate`);
    const tablePoint = bn254.G1.Point.fromAffine({ x, y });
    tablePoint.assertValidity();
    assert(!tablePoint.equals(bn254.G1.Point.ZERO) && tablePoint.isTorsionFree(),
      `table point ${group}:${mask} is not a finite subgroup point`);
    let expected = bn254.G1.Point.ZERO;
    lanePoints.forEach((point, lane) => {
      if (mask & (1 << lane)) expected = expected.add(point.multiplyUnsafe(shift));
    });
    assert(tablePoint.equals(expected), `serialized table mismatch at ${group}:${mask}`);
    checkedTableEntries += 1;
  }
}
assert(checkedTableEntries === 30, 'not every grouped table entry was checked');

// Sparse integer polynomials make the formula checks exact: these are identities
// over Z, so they hold after reduction in Fp. The curve reducer substitutes
// PY^2=PX^3+3PZ^6 and QY^2=QX^3+3 to prove both generated operations preserve
// the curve for every on-curve input, not merely for selected coordinates.
const VARIABLE_COUNT = 5;
const polyMonomial = (exponents, coefficient = 1n) => coefficient === 0n
  ? new Map()
  : new Map([[exponents.join(','), coefficient]]);
const polyConstant = (value) => polyMonomial(Array(VARIABLE_COUNT).fill(0), value);
const polyVariable = (index) => {
  const exponents = Array(VARIABLE_COUNT).fill(0);
  exponents[index] = 1;
  return polyMonomial(exponents);
};
const polyAdd = (...polynomials) => {
  const result = new Map();
  polynomials.forEach((polynomial) => {
    polynomial.forEach((coefficient, monomial) => {
      const sum = (result.get(monomial) ?? 0n) + coefficient;
      if (sum === 0n) result.delete(monomial);
      else result.set(monomial, sum);
    });
  });
  return result;
};
const polyScale = (polynomial, scalar) => {
  const result = new Map();
  polynomial.forEach((coefficient, monomial) => {
    const product = coefficient * scalar;
    if (product !== 0n) result.set(monomial, product);
  });
  return result;
};
const polySubtract = (left, right) => polyAdd(left, polyScale(right, -1n));
const polyMultiply = (left, right) => {
  const result = new Map();
  left.forEach((leftCoefficient, leftMonomial) => {
    const leftExponents = leftMonomial.split(',').map(Number);
    right.forEach((rightCoefficient, rightMonomial) => {
      const rightExponents = rightMonomial.split(',').map(Number);
      const monomial = leftExponents.map((value, index) => value + rightExponents[index]).join(',');
      const coefficient = (result.get(monomial) ?? 0n) + leftCoefficient * rightCoefficient;
      if (coefficient === 0n) result.delete(monomial);
      else result.set(monomial, coefficient);
    });
  });
  return result;
};
const polyPower = (polynomial, exponent) => {
  let result = polyConstant(1n);
  let base = polynomial;
  while (exponent !== 0) {
    if (exponent & 1) result = polyMultiply(result, base);
    base = polyMultiply(base, base);
    exponent >>= 1;
  }
  return result;
};
const assertPolynomialEqual = (left, right, message) => {
  assert(left.size === right.size && [...left].every(([monomial, coefficient]) =>
    right.get(monomial) === coefficient), message);
};
const [PX, PY, PZ, QX, QY] = Array.from({ length: VARIABLE_COUNT }, (_, index) => polyVariable(index));
const reduceOnCurves = (polynomial) => {
  let result = new Map();
  polynomial.forEach((coefficient, monomial) => {
    const exponents = monomial.split(',').map(Number);
    const yPairs = Math.floor(exponents[1] / 2);
    const qyPairs = Math.floor(exponents[4] / 2);
    exponents[1] %= 2;
    exponents[4] %= 2;
    let term = polyMonomial(exponents, coefficient);
    term = polyMultiply(term, polyPower(polyAdd(
      polyPower(PX, 3), polyScale(polyPower(PZ, 6), 3n),
    ), yPairs));
    term = polyMultiply(term, polyPower(polyAdd(
      polyPower(QX, 3), polyConstant(3n),
    ), qyPairs));
    result = polyAdd(result, term);
  });
  return result;
};
const rawMixedAdd = (h, rr, x, y, z) => {
  const hh = polyPower(h, 2);
  const hhh = polyMultiply(h, hh);
  const vv = polyMultiply(x, hh);
  const nx = polySubtract(polySubtract(polyPower(rr, 2), hhh), polyScale(vv, 2n));
  return [
    nx,
    polySubtract(polyMultiply(rr, polySubtract(vv, nx)), polyMultiply(y, hhh)),
    polyMultiply(z, h),
  ];
};

const doubleA = polyPower(PX, 2);
const doubleB = polyPower(PY, 2);
const doubleC = polyPower(doubleB, 2);
const doubleD = polyScale(polyMultiply(PX, doubleB), 4n);
const doubleE = polyScale(doubleA, 3n);
const doubleX = polySubtract(polyPower(doubleE, 2), polyScale(doubleD, 2n));
const doubleY = polySubtract(
  polyMultiply(doubleE, polySubtract(doubleD, doubleX)),
  polyScale(doubleC, 8n),
);
const doubleZ = polyScale(polyMultiply(PY, PZ), 2n);
const expectedTangentX = polySubtract(polyPower(doubleE, 2),
  polyScale(polyMultiply(PX, polyPower(PY, 2)), 8n));
const expectedTangentY = polySubtract(
  polyMultiply(doubleE, polySubtract(polyScale(polyMultiply(PX, polyPower(PY, 2)), 4n), doubleX)),
  polyScale(polyPower(PY, 4), 8n),
);
assertPolynomialEqual(doubleX, expectedTangentX, 'Jacobian double X is not the tangent-law numerator');
assertPolynomialEqual(doubleY, expectedTangentY, 'Jacobian double Y is not the tangent-law numerator');
assert(reduceOnCurves(polySubtract(
  polyPower(doubleY, 2),
  polyAdd(polyPower(doubleX, 3), polyScale(polyPower(doubleZ, 6), 3n)),
)).size === 0, 'Jacobian double does not preserve the BN254 curve equation');

const zSquared = polyPower(PZ, 2);
const h = polySubtract(polyMultiply(QX, zSquared), PX);
const rr = polySubtract(polyMultiply(polyMultiply(QY, zSquared), PZ), PY);
const [addX, addY, addZ] = rawMixedAdd(h, rr, PX, PY, PZ);
const secantX = polySubtract(
  polySubtract(polyPower(rr, 2), polyMultiply(PX, polyPower(h, 2))),
  polyMultiply(polyMultiply(QX, zSquared), polyPower(h, 2)),
);
const secantY = polySubtract(
  polyMultiply(rr, polySubtract(polyMultiply(PX, polyPower(h, 2)), addX)),
  polyMultiply(PY, polyPower(h, 3)),
);
assertPolynomialEqual(addX, secantX, 'mixed-add X is not the secant-law numerator');
assertPolynomialEqual(addY, secantY, 'mixed-add Y is not the secant-law numerator');
assert(reduceOnCurves(polySubtract(
  polyPower(addY, 2),
  polyAdd(polyPower(addX, 3), polyScale(polyPower(addZ, 6), 3n)),
)).size === 0, 'mixed addition does not preserve the BN254 curve equation');

const zero = polyConstant(0n);
const [equalX, equalY, equalZ] = rawMixedAdd(zero, zero, PX, PY, PZ);
assert(equalX.size === 0 && equalY.size === 0 && equalZ.size === 0,
  'equal-point raw addition does not produce the fallback sentinel');
const [inverseX, inverseY, inverseZ] = rawMixedAdd(
  zero, polyScale(PY, -2n), PX, PY, PZ,
);
assertPolynomialEqual(inverseX, polyScale(polyPower(PY, 2), 4n),
  'inverse-add X specialization changed');
assertPolynomialEqual(inverseY, polyScale(polyPower(PY, 3), 8n),
  'inverse-add Y is not -rr^3');
assert(inverseZ.size === 0 && 8n % P !== 0n,
  'inverse addition does not produce nonzero-Y projective infinity');

// Universal induction over every generated transition:
//
//  * Identity/no-add: (0,1,0) starts with nonzero Y; a skipped operation keeps it.
//  * Add to infinity: jacAddAffine returns the selected finite table point.
//  * Double: a finite state has Y,Z != 0, so Z'=2YZ != 0. The result remains
//    in the odd prime-order subgroup and therefore cannot have affine Y=0.
//  * Equal add: h=rr=0 makes raw Y=0, and the exact generated branch above
//    redirects to the proven doubling formula.
//  * Inverse add: h=0 and rr=-2Y give Z'=0 and Y'=8Y^3 != 0.
//  * Ordinary add: h!=0 gives Z'=Zh!=0. The finite result remains in the
//    subgroup, where Y=0 would be nontrivial 2-torsion; gcd(2,R)=1 excludes it.
//
// These cases exhaust Z=0, and for Z!=0 the relations h=0 with rr=0,
// h=0 with rr!=0, and h!=0. Thus every reachable state has invertible Y.

const fixedMiller = Fp12.mul(
  singlePairMiller(pairsFor([0n, 0n], undefined, { msmOnly: true })[1]).f,
  singlePairMiller({ P: vk.ic[0], Q: vk.gamma }).f,
);

// Deterministic end-to-end checks for projective normalization and IC0 folding.
let random = 0x6a09e667f3bcc909n;
for (let index = 0; index < 128; index++) {
  random ^= random << 13n;
  random ^= random >> 7n;
  random ^= random << 17n;
  const in0 = ((random % R) + R) % R;
  random ^= random << 13n;
  random ^= random >> 7n;
  random ^= random << 17n;
  const in1 = ((random % R) + R) % R;
  const scalars = glvDecomposeJoint(in0, in1);
  const [X, Y, Z] = vkxGlvSplitStateAt(...scalars, VKXGLV_SPLIT_ITERS);
  const msm = pairsFor([in0, in1], undefined, { msmOnly: true })[2].P;
  if (Y === 0n) throw new Error(`projective accumulator has zero Y at ${index}`);
  const yInv = Fp.inv(Y);
  const z2 = Fp.sqr(Z);
  const u = Fp.neg(Fp.mul(Fp.mul(X, Z), yInv));
  const v = Fp.neg(Fp.mul(Fp.mul(z2, Z), yInv));
  if (Fp.add(Fp.mul(u, Y), Fp.mul(X, Z)) !== 0n ||
      Fp.add(Fp.mul(v, Y), Fp.mul(z2, Z)) !== 0n) {
    throw new Error(`projective cross-multiplication mismatch at ${index}`);
  }

  if (Z === 0n) {
    if (!msm.equals(bn254.G1.Point.ZERO)) throw new Error(`projective infinity mismatch at ${index}`);
    if (u !== 0n || v !== 0n) throw new Error(`projective infinity is not normalized to zero at ${index}`);
  } else {
    const affine = msm.toAffine();
    const affineYInv = Fp.inv(affine.y);
    if (u !== Fp.neg(Fp.mul(affine.x, affineYInv)) || v !== Fp.neg(affineYInv)) {
      throw new Error(`projective unit-line coordinates mismatch at ${index}`);
    }
  }

  const original = millerBatchOps(pairsFor([in0, in1])).boundary;
  const projective = millerFusedAffineOps(
    pairsFor([in0, in1], undefined, { msmOnly: true }),
    Fp12.ONE,
    Fp12.ONE,
    { unitLines: true, fixedMiller },
  ).boundary;
  if (!Fp12.eql(Fp12.finalExponentiate(original), Fp12.finalExponentiate(projective))) {
    throw new Error(`IC0/projective pairing mismatch at ${index}`);
  }
}

const infinityState = vkxGlvSplitStateAt(
  ...glvDecomposeJoint(0n, 0n), VKXGLV_SPLIT_ITERS,
);
if (infinityState[0] !== 0n || infinityState[1] !== 1n || infinityState[2] !== 0n) {
  throw new Error('canonical zero-input MSM is not the (0,1,0) projective infinity');
}
const originalInfinity = millerBatchOps(pairsFor([0n, 0n])).boundary;
const projectiveInfinity = millerFusedAffineOps(
  pairsFor([0n, 0n], undefined, { msmOnly: true }),
  Fp12.ONE,
  Fp12.ONE,
  { unitLines: true, fixedMiller },
).boundary;
if (!Fp12.eql(Fp12.finalExponentiate(originalInfinity), Fp12.finalExponentiate(projectiveInfinity))) {
  throw new Error('MSM-at-infinity pairing mismatch');
}

console.error('Universal grouped GLV Y-invariant and projective handoff certificate passed');
console.error(`proved p and r prime, cofactor=1, exact grouped kernels, and ${checkedTableEntries} finite table entries`);
console.error('proved identity, finite-table, equal, inverse, ordinary, and doubling transitions preserve Y != 0');
console.error('checked 128 deterministic handoffs and the canonical MSM-at-infinity pairing path');
